// GEOPÓLEM — Dataset interno de focos (hotspots) y nodos del sistema-mundo
// Fuentes abiertas. Prototipo editorial. No sustituye fuentes oficiales.

export const CATEGORIES = {
  conflicto:   { id:'conflicto',  label:'Conflictos',         color:'#ef4444', icon:'⚔' },
  agua:        { id:'agua',       label:'Agua / Clima',       color:'#22d3ee', icon:'≈' },
  energia:     { id:'energia',    label:'Energía',            color:'#f59e0b', icon:'⚡' },
  ia:          { id:'ia',         label:'IA / Narrativa',     color:'#a78bfa', icon:'◬' },
  migracion:   { id:'migracion',  label:'Migración',          color:'#fb923c', icon:'→' },
  salud:       { id:'salud',      label:'Salud',              color:'#34d399', icon:'+' },
  ddhh:        { id:'ddhh',       label:'Derechos Humanos',   color:'#f472b6', icon:'§' },
  sistema:     { id:'sistema',    label:'Sistema-mundo',      color:'#94a3b8', icon:'◯' },
  chokepoint:  { id:'chokepoint', label:'Chokepoint',         color:'#fbbf24', icon:'⌖' },
  defensa:     { id:'defensa',    label:'Defensa / Rearme',   color:'#f97316', icon:'◆' },
};

export const REGIONS = [
  'Europa del Este','MENA','Sahel','Cuerno de África','Asia del Sur',
  'Asia-Pacífico','América Latina','Norteamérica','Eurasia','Global'
];

// Hotspots editoriales (lat/lng aproximados para placement en mapa equirectangular)
export const FOCOS = [
  {
    id: 'rearme-global',
    title: 'Rearme global — gasto militar récord',
    region: 'Global',
    category: 'defensa',
    intensity: 4,
    coords: { lat: 50.0, lng: 10.0 },
    summary: 'El gasto militar mundial alcanzó 2,887 billones de dólares en 2025, con Europa y Asia-Oceanía como zonas de aceleración y una concentración del 51% en EE.UU., China y Rusia.',
    foda: {
      F: ['Disuasión reforzada', 'Base industrial de defensa en expansión', 'Interoperabilidad OTAN acelerada'],
      O: ['Innovación dual-use', 'Reindustrialización europea', 'Nuevas doctrinas de defensa aérea, drones y ciber'],
      D: ['Presión fiscal', 'Dependencia de proveedores críticos', 'Cuellos de botella en munición y semiconductores'],
      A: ['Carreras armamentísticas regionales', 'Militarización de IA y espacio', 'Riesgo de escalada por error de cálculo'],
    },
    pestel: {
      P: 'Competencia sistémica EE.UU.–China–Rusia, rearme europeo y nuevas alianzas regionales.',
      E: 'Desvío presupuestario hacia defensa, presión fiscal y expansión del complejo militar-industrial.',
      S: 'Debate social entre seguridad, bienestar y fatiga de guerra.',
      T: 'Drones, defensa aérea, munición inteligente, IA militar, espacio y guerra electrónica.',
      A: 'Huella industrial, minerales críticos y energía para cadenas de defensa.',
      L: 'Controles de exportación, sanciones, compras públicas y compromisos OTAN.',
    },
    actores: {
      gobiernos: ['EE.UU.','China','Rusia','miembros OTAN','India','Japón','Corea del Sur','Australia'],
      empresas: ['Lockheed Martin','RTX','Northrop Grumman','Rheinmetall','BAE Systems','Leonardo','Thales'],
      organismos: ['SIPRI','OTAN','UE','ONU','OSCE'],
      armados: ['Fuerzas armadas nacionales','mandos conjuntos','comandos espaciales y ciber'],
      sociedad: ['Industria dual-use','universidades','trabajadores defensa','contribuyentes','ONGs de control armamentístico'],
    },
    risks: [
      { name:'Carrera armamentística Europa–Rusia', prob:0.75, impact:0.85, speed:0.55, contain:0.45 },
      { name:'Choque industrial por munición y defensa aérea', prob:0.7, impact:0.65, speed:0.6, contain:0.55 },
      { name:'Escalada Indo-Pacífico', prob:0.45, impact:0.95, speed:0.75, contain:0.35 },
      { name:'Militarización acelerada de IA', prob:0.8, impact:0.75, speed:0.85, contain:0.25 },
    ],
    scenarios: {
      base:        { title:'Rearme sostenido y gestión de disuasión', señales:['Presupuestos plurianuales','Compras conjuntas UE','Aumento producción munición'], indicadores:['Gasto defensa/PIB','Pedidos defensa aérea','Capacidad 155mm'], impacto:{ agua:1, energia:3, alimentos:1, migracion:1, seguridad:4 } },
      escalada:    { title:'Carrera regional acelerada', señales:['Incidentes Báltico/Mar Negro','Crisis Taiwán','Ciberataques críticos'], indicadores:['Alertas OTAN','Movimientos navales','Contratos urgentes'], impacto:{ agua:1, energia:4, alimentos:2, migracion:2, seguridad:5 } },
      ruptura:     { title:'Conflicto entre grandes potencias', señales:['Cierre rutas marítimas','Ataques a satélites','Movilización parcial'], indicadores:['Brent','seguros marítimos','alertas espacio/ciber'], impacto:{ agua:3, energia:5, alimentos:5, migracion:5, seguridad:5 } },
      desescalada: { title:'Control de armas y compras coordinadas', señales:['Canales militares reabiertos','acuerdos export control','transparencia presupuestaria'], indicadores:['Tratados','reducción incidentes','auditorías gasto'], impacto:{ agua:1, energia:2, alimentos:1, migracion:1, seguridad:2 } },
    },
  },
  {
    id: 'ukr-rus',
    title: 'Ucrania – Rusia',
    region: 'Europa del Este',
    category: 'conflicto',
    intensity: 5,
    coords: { lat: 49.0, lng: 32.0 },
    summary: 'Guerra de desgaste con frente estabilizado, presión sobre infraestructura energética y campañas híbridas (cíber, drones, narrativa).',
    foda: {
      F: ['Apoyo OTAN sostenido', 'Industria de drones ucraniana madura', 'Cohesión política interna UA'],
      O: ['Reconstrucción europea coordinada', 'Integración a cadenas industriales UE', 'Estándares de defensa interoperables'],
      D: ['Demografía y reclutamiento', 'Dependencia de ayuda externa', 'Infraestructura energética golpeada'],
      A: ['Fatiga de aliados', 'Escalada nuclear táctica', 'Sabotaje a cables submarinos'],
    },
    pestel: {
      P: 'Presión electoral en aliados clave; ampliación OTAN.',
      E: 'Costes fiscales de reconstrucción y subsidios energéticos.',
      S: 'Desplazamiento masivo y trauma colectivo.',
      T: 'Guerra de drones, EW, IA en targeting.',
      A: 'Daños ambientales severos (Kakhovka, suelos).',
      L: 'Inmunidad estatal, tribunales especiales, sanciones.',
    },
    actores: {
      gobiernos: ['Ucrania', 'Rusia', 'EE.UU.', 'UE', 'Polonia', 'Turquía'],
      empresas: ['Naftogaz', 'Gazprom', 'Lockheed Martin', 'Rheinmetall'],
      organismos: ['OTAN', 'ONU', 'OSCE', 'CPI'],
      armados: ['FFAA UA', 'FFAA RU', 'Wagner/Africa Corps', 'Brigadas voluntarias'],
      sociedad: ['Diáspora UA', 'ONGs humanitarias', 'OSINT (Bellingcat)'],
    },
    risks: [
      { name: 'Escalada nuclear táctica',   prob: 0.15, impact: 0.95, speed: 0.8, contain: 0.3 },
      { name: 'Colapso red eléctrica UA',   prob: 0.55, impact: 0.7,  speed: 0.6, contain: 0.5 },
      { name: 'Sabotaje cables Báltico',    prob: 0.45, impact: 0.6,  speed: 0.9, contain: 0.4 },
      { name: 'Fatiga apoyo occidental',    prob: 0.6,  impact: 0.75, speed: 0.3, contain: 0.5 },
    ],
    scenarios: {
      base:        { title:'Statu quo de desgaste', señales:['Línea de frente <5km/mes','Apoyo militar estable','Inflación controlada'], indicadores:['Producción 155mm','Tasa drones/día','Sanciones nuevas'], impacto:{ agua:1, energia:3, alimentos:2, migracion:2, seguridad:3 } },
      escalada:    { title:'Apertura de frentes y golpes profundos', señales:['Ataques OTAN-este','Movilización RU','Drones largo alcance'], indicadores:['Lanzamientos misiles/sem','Ciberataques críticos','Cierre espacio aéreo'], impacto:{ agua:2, energia:4, alimentos:3, migracion:4, seguridad:5 } },
      ruptura:     { title:'Uso de arma no convencional o colapso de estado', señales:['Empleo táctico nuclear','Crisis sucesoria Kremlin','Defección masiva'], indicadores:['Alertas IAEA','Movimientos cabezas nucleares','Vacío de mando'], impacto:{ agua:3, energia:5, alimentos:4, migracion:5, seguridad:5 } },
      desescalada: { title:'Alto el fuego negociado, congelado', señales:['Canales Estambul/Doha','Intercambios prisioneros','Pausa ataques infra'], indicadores:['Reuniones técnicas','Comercio cereales','Retorno refugiados'], impacto:{ agua:1, energia:2, alimentos:1, migracion:1, seguridad:2 } },
    },
  },
  {
    id: 'isr-gaza-irn',
    title: 'Israel – Gaza – Irán',
    region: 'MENA',
    category: 'conflicto',
    intensity: 5,
    coords: { lat: 31.5, lng: 34.5 },
    summary: 'Crisis humanitaria en Gaza, frentes con Hezbollah y Houthi, intercambio directo Israel–Irán y riesgo de guerra regional.',
    foda: {
      F: ['Superioridad aérea IL', 'Inteligencia regional', 'Apoyo EE.UU.'],
      O: ['Acuerdos Abraham ampliados', 'Normalización con KSA condicionada'],
      D: ['Coste reputacional global', 'Polarización interna IL', 'Frente norte abierto'],
      A: ['Guerra regional Irán', 'Crisis humanitaria Gaza', 'Bloqueo Bab el-Mandeb'],
    },
    pestel: {
      P: 'Crisis legitimidad de actores, presión CIJ/CPI.',
      E: 'Primas riesgo energético, fletes Mar Rojo.',
      S: 'Trauma generacional, refugiados, antisemitismo/islamofobia.',
      T: 'Iron Dome, drones iraníes Shahed, ciberops.',
      A: 'Agua y agricultura Gaza colapsadas.',
      L: 'Casos genocidio CIJ, órdenes de arresto CPI.',
    },
    actores: {
      gobiernos: ['Israel','EE.UU.','Irán','Egipto','Qatar','Arabia Saudí','Turquía'],
      empresas: ['Elbit','Rafael','NSO','Lockheed','navieras Maersk/MSC'],
      organismos: ['ONU','UNRWA','OIEA','CIJ','CPI','Liga Árabe'],
      armados: ['FDI','Hamás','Hezbollah','Houthis','Cuerpos Quds','PMF Iraq'],
      sociedad: ['ONG humanitarias','Diásporas','Movimientos solidaridad'],
    },
    risks: [
      { name: 'Guerra abierta Israel–Irán',   prob: 0.35, impact: 0.95, speed: 0.85, contain: 0.25 },
      { name: 'Cierre Bab el-Mandeb',         prob: 0.5,  impact: 0.8,  speed: 0.9,  contain: 0.4 },
      { name: 'Frente norte Hezbollah total', prob: 0.4,  impact: 0.85, speed: 0.7,  contain: 0.3 },
      { name: 'Crisis humanitaria irreversible', prob: 0.8, impact: 0.9, speed: 0.5, contain: 0.4 },
    ],
    scenarios: {
      base:        { title:'Contención con escaramuzas', señales:['Mediación Qatar/Egipto','Pausas humanitarias','Intercambios limitados'], indicadores:['Convoyes ayuda/día','Lanzamientos Yemen','Reuniones técnicas'], impacto:{ agua:4, energia:3, alimentos:4, migracion:3, seguridad:4 } },
      escalada:    { title:'Frente norte abierto, golpes Irán', señales:['Movilización norte IL','Ataques bases EE.UU.','Drones Shahed sobre IL'], indicadores:['Cierre aeropuertos','Precios Brent','Evacuaciones'], impacto:{ agua:4, energia:5, alimentos:4, migracion:4, seguridad:5 } },
      ruptura:     { title:'Guerra regional con golpes nucleares no declarados', señales:['Ataque a Natanz/Dimona','Cierre Ormuz','Movilización general'], indicadores:['Brent >$130','Cierre rutas aéreas','Alertas OIEA'], impacto:{ agua:5, energia:5, alimentos:5, migracion:5, seguridad:5 } },
      desescalada: { title:'Alto el fuego sostenido + plan reconstrucción', señales:['Acuerdo rehenes/presos','Apertura cruces','Retiro IDF Gaza'], indicadores:['Convoyes/día','Retorno desplazados','Inversión Golfo'], impacto:{ agua:3, energia:2, alimentos:3, migracion:2, seguridad:3 } },
    },
  },
  {
    id: 'sahel',
    title: 'Sahel — Juntas militares y yihadismo',
    region: 'Sahel',
    category: 'conflicto',
    intensity: 4,
    coords: { lat: 14.5, lng: 0.5 },
    summary: 'Eje Mali–Burkina–Níger consolida AES, salida de Francia/CEDEAO, presencia rusa, expansión yihadista al golfo de Guinea.',
    foda: {
      F: ['Recursos críticos (uranio, oro, litio)','Demografía joven','Soberanía discursiva'],
      O: ['Diversificación de socios (RU/CN/TR)','Renta minera renegociada'],
      D: ['Capacidad estatal débil','Infraestructura deficiente','Economías informales'],
      A: ['Expansión JNIM/EIGS','Sequías y desplazamientos','Ruptura cadenas alimentos'],
    },
    pestel: {
      P:'Juntas militares y narrativa anti-colonial.',
      E:'Renta minera, salida CFA, deuda.',
      S:'Desplazados internos, jóvenes sin futuro.',
      T:'Drones turcos Bayraktar, comms degradadas.',
      A:'Desertificación, lago Chad, agua.',
      L:'Salida CEDEAO, salida CPI parcial.',
    },
    actores: {
      gobiernos:['Mali','Burkina Faso','Níger','Chad','Francia','Rusia','EE.UU.','Turquía','China'],
      empresas:['Orano','Barrick','Wagner/Africa Corps comercial'],
      organismos:['CEDEAO','UA','ONU MINUSMA (terminada)','AES'],
      armados:['FFAA juntas','JNIM','EIGS','Wagner/Africa Corps','milicias étnicas'],
      sociedad:['Diáspora','ONGs','OSC locales','líderes religiosos'],
    },
    risks: [
      { name:'Expansión yihadista a Golfo de Guinea', prob:0.65, impact:0.8, speed:0.6, contain:0.4 },
      { name:'Crisis alimentaria Sahel',              prob:0.7,  impact:0.75,speed:0.5, contain:0.5 },
      { name:'Choque junta vs CEDEAO',                prob:0.4,  impact:0.6, speed:0.7, contain:0.5 },
      { name:'Migración forzada hacia Magreb/UE',     prob:0.75, impact:0.7, speed:0.4, contain:0.4 },
    ],
    scenarios: {
      base:        { title:'AES consolida, frontera Golfo de Guinea presionada', señales:['Acuerdos AES','Wagner permanece','Ataques fronterizos'], indicadores:['Atentados/mes','Tropas RU/junta','Precio uranio'], impacto:{ agua:3, energia:3, alimentos:4, migracion:4, seguridad:4 } },
      escalada:    { title:'Caída de capitales costeras a yihadismo', señales:['Ataques Lomé/Cotonou','Refugiados masivos','Golpes adicionales'], indicadores:['Desplazados/sem','Salida ONGs','Cierre fronteras'], impacto:{ agua:4, energia:4, alimentos:5, migracion:5, seguridad:5 } },
      ruptura:     { title:'Estado fallido en cadena, califato territorial', señales:['Control yihadista capitales','Colapso fiscal','Hambruna declarada'], indicadores:['IPC Phase 5','Éxodo','Intervención externa'], impacto:{ agua:5, energia:4, alimentos:5, migracion:5, seguridad:5 } },
      desescalada: { title:'Pacto político regional + ayuda condicionada', señales:['Elecciones calendarizadas','Mediación regional','Retorno cooperación'], indicadores:['Inversión','Retorno IDPs','Reducción ataques'], impacto:{ agua:2, energia:2, alimentos:3, migracion:3, seguridad:3 } },
    },
  },
  {
    id: 'red-sea',
    title: 'Mar Rojo / Bab el-Mandeb',
    region: 'MENA',
    category: 'chokepoint',
    intensity: 4,
    coords: { lat: 12.5, lng: 43.5 },
    summary: 'Ataques Houthi a navegación reducen tráfico ~50%, fletes y primas suben, desvíos por Cabo de Buena Esperanza añaden 10-14 días.',
    foda: {
      F: ['Misiones EUNAVFOR/Prosperity Guardian','Ruta alternativa Cabo'],
      O: ['Reindustrialización portuaria UE','Diversificación logística'],
      D: ['Coste fletes','Emisiones extra','Vulnerabilidad navieras'],
      A: ['Ataques con misiles balísticos antibuque','Minas','Drones marítimos'],
    },
    pestel: {
      P:'Coalición ad-hoc EE.UU./UE; Yemen-Houthi.',
      E:'Fletes +200-400%, primas seguros marítimos.',
      S:'Encarecimiento bienes, presión inflación.',
      T:'Drones marítimos, balísticos antibuque.',
      A:'Más millas, más emisiones GEI.',
      L:'Derecho marítimo, zonas de exclusión.',
    },
    actores: {
      gobiernos:['EE.UU.','Reino Unido','UE','Egipto','Arabia Saudí','Yemen','Irán','China'],
      empresas:['Maersk','MSC','CMA CGM','Hapag-Lloyd','aseguradoras Lloyd\u2019s'],
      organismos:['ONU','OMI','Autoridad Canal Suez','EUNAVFOR Aspides'],
      armados:['Houthis','CENTCOM','Coalición Aspides'],
      sociedad:['Sindicatos marítimos','ONG ambientales'],
    },
    risks: [
      { name:'Cierre efectivo Bab el-Mandeb',    prob:0.5,  impact:0.85, speed:0.9, contain:0.4 },
      { name:'Daño a buque tanque grande',       prob:0.55, impact:0.7,  speed:0.95,contain:0.5 },
      { name:'Escalada Yemen continental',       prob:0.4,  impact:0.6,  speed:0.6, contain:0.5 },
      { name:'Crisis seguros marítimos',         prob:0.6,  impact:0.65, speed:0.7, contain:0.6 },
    ],
    scenarios: {
      base:        { title:'Ataques esporádicos, desvíos sostenidos', señales:['Convoyes coalición','Ataques semanales','Desvíos parciales'], indicadores:['Tráfico Suez','Fletes Shanghai-Rotterdam','Primas K&R'], impacto:{ agua:1, energia:3, alimentos:3, migracion:2, seguridad:3 } },
      escalada:    { title:'Hundimiento mayor, evacuación rutas', señales:['Tanker hundido','Cierre tránsito','Misiles a EE.UU.'], indicadores:['Brent','Seguro guerra','Cierre puertos'], impacto:{ agua:2, energia:5, alimentos:4, migracion:3, seguridad:4 } },
      ruptura:     { title:'Bloqueo total, choque Irán', señales:['Cierre Ormuz vinculado','Ataques Aramco','Movilización Golfo'], indicadores:['Brent >$130','Racionamiento UE','Crisis logística global'], impacto:{ agua:3, energia:5, alimentos:5, migracion:4, seguridad:5 } },
      desescalada: { title:'Cese hostilidades Yemen + acuerdo regional', señales:['Tregua Yemen','Levantamiento bloqueo','Retorno tráfico'], indicadores:['Tráfico Suez recupera','Fletes caen','Primas normalizan'], impacto:{ agua:1, energia:1, alimentos:1, migracion:1, seguridad:2 } },
    },
  },
  {
    id: 'istanbul',
    title: 'Canal de Estambul / Bósforo',
    region: 'Eurasia',
    category: 'chokepoint',
    intensity: 2,
    coords: { lat: 41.0, lng: 29.0 },
    summary: 'Proyecto canal paralelo TR + Convención de Montreux: cuello de botella crítico para grano y petróleo Mar Negro.',
    foda: {
      F:['Soberanía TR sobre estrechos','Acuerdo grano renovable'],
      O:['Hub logístico Trabzon-Estambul','Mediación TR'],
      D:['Riesgo accidente buques','Tensión Montreux'],
      A:['Sabotaje','Cierre por conflicto Mar Negro'],
    },
    pestel: {
      P:'Equilibrio TR–RU–OTAN.',
      E:'25% del comercio mundial de grano.',
      S:'Estambul: megaciudad y riesgo sísmico.',
      T:'Modernización flota mercante.',
      A:'Riesgo ambiental por densidad de tráfico.',
      L:'Convención de Montreux (1936).',
    },
    actores: {
      gobiernos:['Turquía','Rusia','Ucrania','UE','EE.UU.'],
      empresas:['BOTAŞ','Naftogaz','aseguradoras'],
      organismos:['ONU','OMI'],
      armados:['Marina TR','Flota Mar Negro RU'],
      sociedad:['ONG ambientales Estambul','Sindicatos marítimos'],
    },
    risks: [
      { name:'Suspensión tránsito por conflicto',   prob:0.25, impact:0.85, speed:0.9, contain:0.4 },
      { name:'Accidente grave buque tanque',        prob:0.3,  impact:0.7,  speed:0.95,contain:0.6 },
      { name:'Revisión Montreux por presión OTAN',  prob:0.2,  impact:0.6,  speed:0.3, contain:0.5 },
    ],
    scenarios: {
      base:        { title:'Tráfico normal con monitoreo TR', señales:['Acuerdo grano','Tránsito estable'], indicadores:['Buques/día','Tarifas paso'], impacto:{ agua:1, energia:2, alimentos:3, migracion:1, seguridad:2 } },
      escalada:    { title:'Restricciones por incidente naval RU/UA', señales:['Minas a la deriva','Cierre temporal'], indicadores:['Días cerrado','Cola buques'], impacto:{ agua:1, energia:3, alimentos:4, migracion:1, seguridad:3 } },
      ruptura:     { title:'Cierre indefinido, crisis grano', señales:['Conflicto Mar Negro abierto','Bloqueo Odesa'], indicadores:['Precio trigo CBOT','Crisis MENA/África'], impacto:{ agua:2, energia:4, alimentos:5, migracion:3, seguridad:4 } },
      desescalada: { title:'Acuerdo plurianual de tránsito y grano', señales:['Renovación acuerdo','Seguros estables'], indicadores:['Tráfico normaliza','Precio grano cae'], impacto:{ agua:1, energia:1, alimentos:1, migracion:1, seguridad:1 } },
    },
  },
  {
    id: 'mena-agua',
    title: 'MENA — Estrés hídrico estructural',
    region: 'MENA',
    category: 'agua',
    intensity: 4,
    coords: { lat: 30.0, lng: 38.0 },
    summary: 'Jordán, Eufrates–Tigris, Nilo, acuíferos fósiles agotándose. 12 de 17 países con mayor estrés hídrico del mundo están en MENA.',
    foda: {
      F:['Capital árabe para desalación','Solar abundante'],
      O:['Hidrógeno verde','Reutilización aguas grises'],
      D:['Subsidios distorsionan demanda','Pérdidas de red'],
      A:['Guerras del agua','Migración climática','Fallo cosechas'],
    },
    pestel: {
      P:'Disputas transfronterizas (GERD, Eufrates).',
      E:'Coste desalación, soberanía alimentaria.',
      S:'Éxodo rural, calor extremo.',
      T:'Desalación, drip irrigation, reúso.',
      A:'Sequías multianuales, salinización.',
      L:'Derecho internacional aguas compartidas débil.',
    },
    actores: {
      gobiernos:['Egipto','Etiopía','Sudán','Turquía','Irán','Irak','Siria','Arabia Saudí','Israel','Jordania'],
      empresas:['ACWA Power','Veolia','Suez','IDE Technologies'],
      organismos:['FAO','UN-Water','Banco Mundial','UNESCWA'],
      armados:['No estatales en Mesopotamia','milicias regionales'],
      sociedad:['Movimientos campesinos','jóvenes climáticos'],
    },
    risks: [
      { name:'Día cero capital MENA',                prob:0.4,  impact:0.85, speed:0.4, contain:0.5 },
      { name:'Conflicto agua transfronterizo',       prob:0.45, impact:0.8,  speed:0.5, contain:0.5 },
      { name:'Crisis alimentaria regional',          prob:0.6,  impact:0.8,  speed:0.4, contain:0.5 },
      { name:'Migración climática masiva',           prob:0.7,  impact:0.7,  speed:0.3, contain:0.4 },
    ],
    scenarios: {
      base:        { title:'Deterioro lento + inversión desalación', señales:['Megaproyectos desalación','Subsidios eficiencia'], indicadores:['Capacidad desal/cápita','Pérdidas red','Lluvias'], impacto:{ agua:5, energia:3, alimentos:4, migracion:3, seguridad:3 } },
      escalada:    { title:'Sequía multianual + choque GERD/Eufrates', señales:['Restricciones agua urbana','Cosechas malas','Tensión TR–IQ'], indicadores:['Caudales','Reservas presas','Precios trigo local'], impacto:{ agua:5, energia:3, alimentos:5, migracion:4, seguridad:4 } },
      ruptura:     { title:'Día cero capital + éxodo regional', señales:['Cortes agua urbana','Disturbios','Movilización ejército'], indicadores:['Días sin suministro','IDPs','Importaciones grano'], impacto:{ agua:5, energia:4, alimentos:5, migracion:5, seguridad:5 } },
      desescalada: { title:'Acuerdos cuenca + financiación verde', señales:['Tratados cuenca','Bonos climáticos','Cooperación tech'], indicadores:['Acuerdos firmados','Inversión $/año','Eficiencia uso'], impacto:{ agua:3, energia:2, alimentos:3, migracion:2, seguridad:2 } },
    },
  },
  {
    id: 'asia-agua',
    title: 'Asia del Sur — Glaciares e Indo',
    region: 'Asia del Sur',
    category: 'agua',
    intensity: 4,
    coords: { lat: 30.0, lng: 78.0 },
    summary: 'Retroceso de glaciares HKH alimenta Ganges, Indo, Brahmaputra. Tratado del Indo bajo presión IN–PK. Calor extremo y monzón errático.',
    foda: {
      F:['Tratado Indo (1960) aún vigente','Cooperación científica HKH'],
      O:['Sistemas alerta temprana','Riego eficiente','Reforestación'],
      D:['Sobreexplotación acuíferos','Contaminación industrial','Infra obsoleta'],
      A:['GLOF (desbordes glaciares)','Guerra IN–PK por agua','Inundaciones súbitas'],
    },
    pestel: {
      P:'India–Pakistán; China upstream.',
      E:'Agro 50% empleo regional.',
      S:'700M+ dependen de estos ríos.',
      T:'Sensores remotos, IA hidrológica.',
      A:'Pico de agua en HKH ~2050.',
      L:'Tratado Indo, revisión solicitada por IN.',
    },
    actores: {
      gobiernos:['India','Pakistán','China','Bangladés','Nepal','Bután'],
      empresas:['Hidroeléctricas IN/CN','agrotech'],
      organismos:['ICIMOD','IPCC','Banco Mundial','SAARC'],
      armados:['FFAA IN','FFAA PK'],
      sociedad:['Campesinos','urbanitas Delhi/Karachi','climáticos'],
    },
    risks: [
      { name:'Ruptura Tratado del Indo',            prob:0.3,  impact:0.85, speed:0.6, contain:0.4 },
      { name:'GLOF catastrófica',                   prob:0.45, impact:0.75, speed:0.95,contain:0.3 },
      { name:'Monzón fallido multianual',           prob:0.4,  impact:0.85, speed:0.3, contain:0.4 },
      { name:'Crisis hambruna Pakistán',            prob:0.5,  impact:0.8,  speed:0.4, contain:0.4 },
    ],
    scenarios: {
      base:        { title:'Estrés creciente, acuerdos parciales', señales:['Diálogo técnico IN–PK','Inversión riego'], indicadores:['Caudal Indo','Cosechas','Mortalidad calor'], impacto:{ agua:4, energia:3, alimentos:4, migracion:3, seguridad:3 } },
      escalada:    { title:'IN suspende Tratado, China presiona Brahmaputra', señales:['Notificación IN','Embalses CN','Maniobras militares'], indicadores:['Caudal anómalo','Cosechas PK','Movimientos tropas'], impacto:{ agua:5, energia:3, alimentos:5, migracion:4, seguridad:4 } },
      ruptura:     { title:'Conflicto agua + crisis alimentaria Pakistán', señales:['Choques fronterizos','Disturbios urbanos','Default PK'], indicadores:['Reservas grano PK','IDPs','Conflicto Cachemira'], impacto:{ agua:5, energia:4, alimentos:5, migracion:5, seguridad:5 } },
      desescalada: { title:'Tratado HKH ampliado + inversión clima', señales:['Cooperación HKH','Bonos catástrofe','Reforestación'], indicadores:['Acuerdos','Inversión $/año','Indicadores ambientales'], impacto:{ agua:2, energia:2, alimentos:2, migracion:1, seguridad:1 } },
    },
  },
  {
    id: 'stablecoins',
    title: 'Stablecoins / desinformación financiera',
    region: 'Global',
    category: 'ia',
    intensity: 3,
    coords: { lat: 40.7, lng: -74.0 },
    summary: 'Crecimiento de stablecoins USD-pegged como infraestructura paralela, riesgo de corrida + bots/IA amplificando narrativas de pánico.',
    foda: {
      F:['Liquidez 24/7','Inclusión cross-border'],
      O:['Regulación clara (MiCA, GENIUS Act)','Rieles instituciones'],
      D:['Concentración Tether/Circle','Opacidad reservas'],
      A:['Corrida + desinformación coordinada','Sanciones evadidas'],
    },
    pestel: {
      P:'EE.UU. vs UE vs CN — soberanía monetaria.',
      E:'>$200B en circulación, sistémicamente relevante.',
      S:'Adopción en países de moneda débil.',
      T:'IA generativa amplifica FUD; on-chain forensics.',
      A:'Huella energética (validadores).',
      L:'MiCA UE, GENIUS Act US, FATF.',
    },
    actores: {
      gobiernos:['EE.UU. (OCC/SEC)','UE (ESMA)','China','Singapur','Emiratos'],
      empresas:['Tether','Circle','PayPal','Visa','BlackRock'],
      organismos:['FSB','FATF','BIS','IMF'],
      armados:['Ninguno (riesgo ciber)','OFAC'],
      sociedad:['Cripto-Twitter','medios financieros','DAOs'],
    },
    risks: [
      { name:'Corrida USDT/USDC',                   prob:0.2,  impact:0.9,  speed:0.95,contain:0.4 },
      { name:'Campaña desinformación coordinada',   prob:0.7,  impact:0.6,  speed:0.9, contain:0.5 },
      { name:'Sanción a emisor major',              prob:0.25, impact:0.75, speed:0.7, contain:0.5 },
      { name:'Hackeo masivo bridge',                prob:0.6,  impact:0.55, speed:0.95,contain:0.6 },
    ],
    scenarios: {
      base:        { title:'Crecimiento regulado, dominio USD', señales:['MiCA aplicada','Auditorías reservas','Custodia bancaria'], indicadores:['Capitalización','Volumen','Reservas T-bills'], impacto:{ agua:0, energia:1, alimentos:0, migracion:0, seguridad:2 } },
      escalada:    { title:'Crisis depeg + campaña FUD viral', señales:['Depeg <0.97','Tendencias X coordinadas','Retiros masivos'], indicadores:['Spread on/off','Volumen retiros','Menciones bots'], impacto:{ agua:0, energia:1, alimentos:1, migracion:1, seguridad:3 } },
      ruptura:     { title:'Colapso emisor mayor + contagio cripto/banca', señales:['Bancarrota emisor','Suspensión redenciones','Quiebra exchanges'], indicadores:['Capitalización','BTC drawdown','Bancos expuestos'], impacto:{ agua:0, energia:1, alimentos:1, migracion:2, seguridad:4 } },
      desescalada: { title:'Marco global armonizado + CBDC interoperables', señales:['Acuerdo FSB','Pilotos CBDC','Estándares reservas'], indicadores:['Adopción institucional','Reducción volatilidad'], impacto:{ agua:0, energia:1, alimentos:0, migracion:0, seguridad:1 } },
    },
  },
  {
    id: 'ia-narrativa',
    title: 'IA / Riesgo narrativo global',
    region: 'Global',
    category: 'ia',
    intensity: 4,
    coords: { lat: 37.4, lng: -122.0 },
    summary: 'IA generativa industrializa desinformación: deepfakes electorales, propaganda multilingüe, manipulación de mercados y emocionalización de conflictos.',
    foda: {
      F:['Detección IA mejora','Estándares C2PA','Watermarking'],
      O:['Regulación EU AI Act','Alfabetización mediática','OSINT asistida'],
      D:['Asimetría coste atacante/defensor','Plataformas reducen moderación'],
      A:['Deepfakes en elecciones','Erosión confianza institucional','Bots autónomos'],
    },
    pestel: {
      P:'Elecciones >70 países 2024-25 expuestas.',
      E:'Manipulación de mercados por IA.',
      S:'Polarización, desconfianza generalizada.',
      T:'GenAI multimodal, agentes autónomos.',
      A:'Consumo energético entrenamiento.',
      L:'EU AI Act, DSA, ley anti-deepfake EE.UU.',
    },
    actores: {
      gobiernos:['EE.UU.','UE','China','Reino Unido','India','Brasil'],
      empresas:['OpenAI','Anthropic','Google','Meta','xAI','ByteDance'],
      organismos:['UNESCO','OCDE','GPAI','UN AI Advisory Body'],
      armados:['Cibercomandos','operadores PsyOps','APTs'],
      sociedad:['Verificadores','academia','periodistas','OSINT'],
    },
    risks: [
      { name:'Deepfake decisivo en elección',        prob:0.7,  impact:0.85, speed:0.95,contain:0.4 },
      { name:'Bot-net IA manipulando mercados',      prob:0.5,  impact:0.7,  speed:0.9, contain:0.5 },
      { name:'Colapso confianza fuentes oficiales',  prob:0.65, impact:0.8,  speed:0.4, contain:0.4 },
      { name:'Incidente AGI / capacidad disruptiva', prob:0.15, impact:0.95, speed:0.5, contain:0.2 },
    ],
    scenarios: {
      base:        { title:'Regulación parcial, ataques continuos', señales:['EU AI Act vigente','Sellos C2PA','Detección mejora'], indicadores:['Volumen deepfakes','Tasa detección','Confianza encuestas'], impacto:{ agua:0, energia:2, alimentos:0, migracion:1, seguridad:4 } },
      escalada:    { title:'Crisis electoral por deepfake + manipulación masas', señales:['Deepfake líder','Bots virales','Choques calle'], indicadores:['Engagement bots','Disturbios','Banneos plataformas'], impacto:{ agua:0, energia:2, alimentos:0, migracion:1, seguridad:5 } },
      ruptura:     { title:'Cascada desinformación + incidente IA crítica', señales:['Manipulación bursátil masiva','Apagones info','Pánicos coord.'], indicadores:['Volatilidad VIX','Cortes plataformas','Movilización gobiernos'], impacto:{ agua:0, energia:3, alimentos:1, migracion:2, seguridad:5 } },
      desescalada: { title:'Estándar global C2PA + alfabetización masiva', señales:['Acuerdo G7+G20','Curriculum escolar','Watermarking obligatorio'], indicadores:['Adopción C2PA','Confianza recuperada','Reducción virales'], impacto:{ agua:0, energia:1, alimentos:0, migracion:0, seguridad:2 } },
    },
  },
];

export const SYSTEMA_NODES = [
  { id:'energy',   label:'Energía',      x:0.18, y:0.35, color:'#f59e0b' },
  { id:'food',     label:'Alimentos',    x:0.35, y:0.6,  color:'#84cc16' },
  { id:'water',    label:'Agua',         x:0.5,  y:0.3,  color:'#22d3ee' },
  { id:'trade',    label:'Comercio',     x:0.65, y:0.55, color:'#a78bfa' },
  { id:'data',     label:'Datos / Cables', x:0.8,  y:0.35, color:'#38bdf8' },
  { id:'migration',label:'Migración',    x:0.35, y:0.15, color:'#fb923c' },
  { id:'finance',  label:'Finanzas',     x:0.8,  y:0.7,  color:'#f472b6' },
  { id:'climate',  label:'Clima',        x:0.5,  y:0.85, color:'#34d399' },
];

export const SYSTEMA_LINKS = [
  ['energy','trade'],['energy','food'],['water','food'],['water','energy'],
  ['climate','water'],['climate','migration'],['climate','food'],
  ['trade','finance'],['data','finance'],['data','trade'],
  ['food','migration'],['energy','climate'],['trade','migration'],
  ['water','migration'],['finance','energy'],
];

export const BRIEF_DIARIO = [
  { tema:'defensa',   headline:'SIPRI: gasto militar mundial toca récord histórico', cuerpo:'El tablero entra en fase de rearme estructural: Europa acelera, Asia-Oceanía aumenta y el top 3 concentra más de la mitad del gasto mundial.' },
  { tema:'conflicto', headline:'Ucrania: presión sobre red eléctrica entra en fase invernal', cuerpo:'Drones rusos golpean subestaciones críticas. Apoyo aliado en revisión política tras elecciones. Sin cambio en línea de frente.' },
  { tema:'conflicto', headline:'Gaza: ventana negociadora se estrecha', cuerpo:'Qatar y Egipto mantienen canal abierto pero crece riesgo norte (Hezbollah) y golpes recíprocos Israel–Irán.' },
  { tema:'chokepoint',headline:'Bab el-Mandeb: tráfico Suez sigue 40% por debajo del baseline', cuerpo:'Fletes Shanghai–Rotterdam +180% YoY. Aseguradoras endurecen primas K&R.' },
  { tema:'agua',      headline:'Sahel: ciclo seco prolonga IPC fase 4 en Burkina', cuerpo:'IDPs superan 2.1M. Corredores humanitarios bajo ataque JNIM.' },
  { tema:'energia',   headline:'Europa: almacenamiento gas al 92%, LNG marginal vulnerable', cuerpo:'Choque MENA o frío severo aún pueden empujar TTF arriba de 60 EUR/MWh.' },
  { tema:'ia',        headline:'Deepfakes electorales: pico detección en última semana', cuerpo:'Plataformas reportan +60% take-downs vs trimestre previo. Auditorías C2PA aún voluntarias.' },
  { tema:'migracion', headline:'Mediterráneo central: rutas se reactivan con clima', cuerpo:'Llegadas a Lampedusa repuntan. Túnez–Italia y Libia–Italia siguen siendo corredores principales.' },
  { tema:'salud',     headline:'Mpox clado Ib: expansión sostenida en África central', cuerpo:'OMS mantiene PHEIC. Cobertura vacunal lejos de objetivo. Riesgo de saltos a Europa.' },
  { tema:'ddhh',      headline:'CIJ y CPI: cascada de decisiones técnicas en curso', cuerpo:'Casos Sudáfrica vs Israel y órdenes de arresto siguen tensionando alianzas occidentales.' },
];

export const KPIS = [
  { id:'milex',       label:'Gasto militar mundial', value:'$2.887T', trend:'+2.9%', tone:'orange', sub:'SIPRI 2025' },
  { id:'conflictos',  label:'Conflictos activos',   value:56, trend:'+3', tone:'red',   sub:'monitoreo OSINT' },
  { id:'agua',        label:'Estrés hídrico',       value:'4.0B', trend:'↑', tone:'cyan',  sub:'personas a 2025' },
  { id:'chokepoints', label:'Chokepoints en riesgo',value:7,  trend:'↑', tone:'amber', sub:'sobre 12 críticos' },
  { id:'energia',     label:'Brent referencia',     value:'$83', trend:'±', tone:'amber', sub:'volatilidad alta' },
  { id:'migracion',   label:'Desplazados forzados', value:'120M', trend:'↑', tone:'orange', sub:'ACNUR 2024' },
  { id:'ia',          label:'Deepfakes detectados', value:'+60%', trend:'↑', tone:'violet', sub:'trimestre' },
  { id:'salud',       label:'Emergencias PHEIC',    value:2,  trend:'=', tone:'green', sub:'mpox, polio' },
  { id:'ddhh',        label:'Países en alerta DDHH',value:34, trend:'↑', tone:'pink',  sub:'Freedom House' },
];

export const MILEX = {
  year: 2025,
  sourceName: 'SIPRI Military Expenditure Database / Press Release 2026',
  sourceUrl: 'https://www.sipri.org/media/press-release/2026/global-military-spending-rise-continues-european-and-asian-expenditures-surge',
  databaseUrl: 'https://www.sipri.org/databases/milex',
  global: [
    { label:'Gasto mundial', value:'$2.887T', note:'2,887 billones USD en 2025' },
    { label:'Crecimiento real', value:'+2.9%', note:'vs. 2024' },
    { label:'Carga sobre PIB', value:'2.5%', note:'máximo desde 2009' },
    { label:'Años de aumento', value:'11', note:'aumento consecutivo' },
  ],
  topThree: [
    { country:'Estados Unidos', spending:954, label:'$954B', note:'-7.5% interanual' },
    { country:'China', spending:336, label:'$336B', note:'+7.4% interanual' },
    { country:'Rusia', spending:190, label:'$190B', note:'+5.9% interanual' },
  ],
  concentration: { value:'$1.480T', share:'51%', note:'EE.UU. + China + Rusia' },
  regions: [
    { region:'Europa', spending:864, label:'$864B', growth:'+14%', tone:'red' },
    { region:'Asia y Oceanía', spending:681, label:'$681B', growth:'+8.1%', tone:'amber' },
    { region:'Oriente Medio', spending:218, label:'$218B', growth:'+0.1%', tone:'cyan' },
    { region:'África', spending:58.2, label:'$58.2B', growth:'+8.5%', tone:'orange' },
  ],
  analysis: [
    'El rearme ya no es un fenómeno aislado: funciona como una infraestructura del sistema-mundo que conecta industria, energía, minerales críticos, deuda pública y doctrina militar.',
    'La lectura GEOPÓLEM no es “más gasto equivale a más seguridad”; el punto crítico es dónde se acelera el gasto, qué capacidades se compran y qué señales cruzan el umbral de disuasión a escalada.',
    'Para 2026–2027, la variable decisiva será la capacidad industrial: munición, defensa aérea, drones, sensores, ciber, espacio y resiliencia energética.'
  ],
  watch: ['Compromisos OTAN sobre PIB', 'pedidos de defensa aérea', 'producción 155mm', 'contratos de drones', 'export controls dual-use', 'incidentes Báltico / Mar Negro / Taiwán'],
};

/* ========================================================================
   DOCTRINA GEOPÓLEM — Tripolaridad imperfecta con multipolaridad periférica
   Marco analítico permanente. Conectado a SENTINEL como capa de lectura.
   Vídeo largo + Short teaser referenciados para CTA/embed.
   ======================================================================== */
export const DOCTRINA = {
  id: 'tripolaridad-imperfecta',
  slug: 'tripolaridad-imperfecta',
  category: 'doctrina',
  tone: 'violet',
  eyebrow: 'Doctrina GEOPÓLEM',
  eyebrowEn: 'GEOPÓLEM Doctrine',
  title: 'Tripolaridad imperfecta',
  titleEn: 'Imperfect Tripolarity',
  subtitle: 'con multipolaridad periférica',
  subtitleEn: 'with peripheral multipolarity',
  summary: 'El mundo no es simplemente multipolar. GEOPÓLEM lo lee como una tripolaridad imperfecta con multipolaridad periférica: tres potencias estructuran el tablero, mientras el resto maniobra en sus márgenes.',
  summaryEn: 'The world is not simply multipolar. GEOPÓLEM reads it as an imperfect tripolarity with peripheral multipolarity: three powers structure the board while the rest maneuver at its margins.',
  // La pregunta analítica central de la doctrina
  question: 'La pregunta no es solo cuántos actores existen, sino quién estructura, quién maniobra y quién acelera.',
  questionEn: 'The question is not just how many actors exist, but who structures, who maneuvers, and who accelerates.',
  // Pilares del tablero. role: 'structure' | 'normative' | 'maneuver'
  pillars: [
    {
      id: 'eeuu',
      actor: 'Estados Unidos',
      actorEn: 'United States',
      role: 'structure',
      function: 'Estructura',
      functionEn: 'Structures',
      accent: '#22d3ee',
      domains: ['Alianzas', 'Finanzas', 'Poder militar', 'Sanciones', 'Arquitectura de mando'],
      domainsEn: ['Alliances', 'Finance', 'Military power', 'Sanctions', 'Command architecture'],
    },
    {
      id: 'china',
      actor: 'China',
      actorEn: 'China',
      role: 'structure',
      function: 'Estructura',
      functionEn: 'Structures',
      accent: '#ef4444',
      domains: ['Producción', 'Infraestructura', 'Deuda', 'Tecnología', 'Escala comercial'],
      domainsEn: ['Production', 'Infrastructure', 'Debt', 'Technology', 'Commercial scale'],
    },
    {
      id: 'rusia',
      actor: 'Rusia',
      actorEn: 'Russia',
      role: 'structure',
      function: 'Estructura',
      functionEn: 'Structures',
      accent: '#f59e0b',
      domains: ['Disrupción', 'Energía', 'Presión militar', 'Veto estratégico'],
      domainsEn: ['Disruption', 'Energy', 'Military pressure', 'Strategic veto'],
    },
    {
      id: 'ue',
      actor: 'Unión Europea',
      actorEn: 'European Union',
      role: 'normative',
      function: 'Potencia normativa',
      functionEn: 'Normative power',
      accent: '#a78bfa',
      domains: ['Regulación', 'Estándares', 'Poder normativo'],
      domainsEn: ['Regulation', 'Standards', 'Normative power'],
    },
    {
      id: 'sur-global',
      actor: 'Sur Global',
      actorEn: 'Global South',
      role: 'maneuver',
      function: 'Maniobra y arbitraje',
      functionEn: 'Maneuver & arbitrage',
      accent: '#10b981',
      domains: ['Maniobra', 'Arbitraje', 'Autonomía estratégica', 'Competencia entre potencias'],
      domainsEn: ['Maneuver', 'Arbitrage', 'Strategic autonomy', 'Power competition'],
    },
  ],
  // Ejes de lectura: quién estructura / maniobra / acelera
  axes: [
    { id:'structure', label:'Quién estructura', labelEn:'Who structures', desc:'EE.UU., China y Rusia fijan las reglas, los flujos y los umbrales del tablero.', descEn:'The US, China and Russia set the rules, flows and thresholds of the board.' },
    { id:'maneuver',  label:'Quién maniobra',   labelEn:'Who maneuvers',  desc:'La UE como potencia normativa y el Sur Global arbitran entre potencias para ganar autonomía.', descEn:'The EU as normative power and the Global South arbitrate between powers to gain autonomy.' },
    { id:'accelerate',label:'Quién acelera',    labelEn:'Who accelerates',desc:'La disrupción, la energía y la presión militar aceleran o congelan los ciclos de crisis.', descEn:'Disruption, energy and military pressure accelerate or freeze crisis cycles.' },
  ],
  // Conexión con el feed SENTINEL (no altera los datos, añade capa de lectura)
  sentinel: {
    label: 'Capa de lectura SENTINEL',
    labelEn: 'SENTINEL reading layer',
    note: 'Los eventos de conflicto de SENTINEL se leen con esta doctrina: quién estructura el incidente, quién lo aprovecha para maniobrar y quién lo acelera.',
    noteEn: 'SENTINEL conflict events are read through this doctrine: who structures the incident, who exploits it to maneuver, and who accelerates it.',
  },
  videos: {
    long:  { id:'ii_PIdlupZE', url:'https://www.youtube.com/watch?v=ii_PIdlupZE', label:'Análisis completo', labelEn:'Full analysis' },
    short: { id:'tLni47YWTDw', url:'https://www.youtube.com/watch?v=tLni47YWTDw', label:'Short · teaser', labelEn:'Short · teaser' },
  },
  tags: ['tripolaridad', 'multipolaridad', 'sistema-mundo', 'EE.UU.', 'China', 'Rusia', 'UE', 'Sur Global', 'doctrina'],
  close: 'GEOPÓLEM. Bienvenidos al tablero.',
};

/* ========================================================================
   SENTINEL · Brief semanal de inflexiones conflicto-ambiente
   Capa que cruza el feed SENTINEL/GDELT con NASA EONET, USGS y fuentes
   institucionales. Acoples confirmados vs. en observación.
   Fuente consumible: ./data/sentinel/weekly-brief.json
   IMPORTANTE: correlación temporal no implica causalidad.
   ======================================================================== */
export const SENTINEL_BRIEF = {
  brand: 'GEOPÓLEM',
  eyebrow: 'GEOPÓLEM SENTINEL',
  eyebrowEn: 'GEOPÓLEM SENTINEL',
  title: 'Brief semanal de inflexiones conflicto-ambiente',
  titleEn: 'Weekly conflict-environment inflection brief',
  generatedAt: '2026-07-20T08:11:00+02:00',
  window: '13 – 19 de julio de 2026 · Europe/Luxembourg',
  windowEn: 'July 13 – 19, 2026 · Europe/Luxembourg',
  dataUrl: './data/sentinel/weekly-brief.json',
  status: 'Acoples activos por vía institucional · cruce automático sin match',
  statusEn: 'Active couplings via institutional sources · automatic cross-match null',
  summary: 'Estado principal de la semana: hay acoples conflicto-ambiente activos, pero se sostienen por fuentes institucionales, no por el cruce automático. El feed SENTINEL trajo 4 eventos de conflicto (Ucrania, Gaza, Taiwán, Malí) sin fecha ni coordenadas utilizables y de tipo ejemplo, de modo que el cruce geoespacial automático dio candidate_matches = 0. NASA (EONET abierto 67, cerrado 73) y USGS (145 sismos M4.5+) sí devolvieron datos válidos, pero sin coincidencia geoespacial verificable con SENTINEL. Sobre esa base institucional se publican tres puntos: Myanmar (naufragio rohinyá, confirmado), Siria (Alepo/Éufrates, operativo) y R. D. Congo (Ébola en Ituri con calor y sequedad, en observación). Se distingue acople operativo de causalidad.',
  summaryEn: 'Main status this week: conflict-environment couplings are active, but they rest on institutional sources rather than the automatic cross-match. The SENTINEL feed returned 4 conflict events (Ukraine, Gaza, Taiwan, Mali) with no usable date or coordinates and example-type items, so the automatic geospatial cross-match yielded candidate_matches = 0. NASA (EONET open 67, closed 73) and USGS (145 M4.5+ quakes) did return valid data, but with no verifiable geospatial match to SENTINEL. On that institutional basis, three points are published: Myanmar (Rohingya boat sinking, confirmed), Syria (Aleppo/Euphrates, operational) and DR Congo (Ebola in Ituri with heat and dryness, under observation). Operational coupling is kept distinct from causation.',
  caveat: 'El cruce automático SENTINEL↔NASA/USGS dio candidate_matches = 0: los 4 eventos de conflicto del feed carecían de fecha y coordenadas utilizables y eran ítems de ejemplo. Los tres puntos se sostienen con fuentes institucionales humanitarias (IOM/UNHCR, UNFPA, OCHA, FEWS NET), no con el match automático. Se distingue acople operativo de causalidad; no se inventaron correlaciones.',
  caveatEn: 'The automatic SENTINEL↔NASA/USGS cross-match returned candidate_matches = 0: the 4 feed conflict events lacked usable date and coordinates and were example items. The three points rest on institutional humanitarian sources (IOM/UNHCR, UNFPA, OCHA, FEWS NET), not on the automatic match. Operational coupling is kept distinct from causation; no correlations were fabricated.',
  stats: [
    { label: 'Eventos SENTINEL en ventana', labelEn: 'SENTINEL events in window', value: '4' },
    { label: 'Coincidencias automáticas', labelEn: 'Automatic candidate matches', value: '0' },
    { label: 'Sismos USGS M4.5+', labelEn: 'USGS M4.5+ quakes', value: '145' },
    { label: 'NASA EONET (abiertos/cerrados)', labelEn: 'NASA EONET (open/closed)', value: '67/73' },
  ],
  points: [
    {
      id: 'myanmar-maritimo-rakhine',
      rank: 1,
      status: 'confirmado',
      statusEn: 'confirmed',
      priority: 'alta',
      priorityEn: 'high',
      accent: '#f87171',
      location: 'Myanmar · Rakhine-Ayeyarwady · ruta marítima a Cox’s Bazar',
      headline: 'Myanmar: naufragio rohinyá con más de 500 desaparecidos',
      headlineEn: 'Myanmar: Rohingya boat sinking, over 500 feared dead',
      fact: 'IOM y UNHCR expresan profunda preocupación por incidentes marítimos frente a la costa de Myanmar. Tras el desplazamiento por conflicto desde Rakhine a finales de junio de 2026, una embarcación habría naufragado frente a Ayeyarwady el 8 de julio y se teme la muerte de más de 500 personas. La travesía ocurrió fuera de la temporada regular de navegación, con lluvias torrenciales e inundaciones recientes que elevaron el riesgo marítimo.',
      coupling: 'Acople operativo confirmado por fuente institucional: el conflicto y el desplazamiento empujan salidas marítimas hacia una ventana ambiental letal; no se afirma causalidad del clima sobre el conflicto.',
      couplingEn: 'Operational coupling confirmed by an institutional source: conflict and displacement push maritime departures into a lethal environmental window; no claim of climate causing the conflict.',
      implication: 'La violencia y el desplazamiento forzado empujan las salidas marítimas, mientras las condiciones ambientales adversas (fuera de temporada, lluvia torrencial, inundaciones) multiplican la letalidad de la ruta. La evidencia respalda acoplamiento operativo, no relación causal. Mientras persista el conflicto y no haya vías seguras, es previsible que las salidas sigan chocando con ventanas meteorológicas peligrosas.',
      tripolar: 'China observa Myanmar por conectividad estratégica hacia el Índico; EE.UU. y la UE por sanciones, gobernanza y protección; Bangladesh, ASEAN y el Sur Global cargan el coste humanitario y de estabilidad regional.',
      sources: [
        { label: 'IOM & UNHCR · ReliefWeb', url: 'https://reliefweb.int/report/myanmar/iom-and-unhcr-deeply-concerned-reports-maritime-incidents-myanmar-coast-over-500-feared-dead' },
        { label: 'GEOPÓLEM SENTINEL', url: 'https://mdiaznaranjo-a11y.github.io/geopolem-public-site/data/sentinel/conflict-events.json' },
      ],
    },
    {
      id: 'siria-alepo-eufrates',
      rank: 2,
      status: 'operativo',
      statusEn: 'operational',
      priority: 'media-alta',
      priorityEn: 'medium-high',
      accent: '#38bdf8',
      location: 'Siria · Alepo, noreste y corredor del Éufrates',
      headline: 'Siria: hostilidades e inundaciones del Éufrates sobre 1,2 M en necesidad',
      headlineEn: 'Syria: hostilities and Euphrates floods over 1.2M in urgent need',
      fact: 'El situation report de UNFPA Siria publicado el 8 de julio de 2026 (cobertura mayo-junio) reporta hostilidades renovadas en Alepo y el noreste junto a inundaciones severas en el corredor del Éufrates, con servicios públicos tensionados y 1,2 millones de personas en necesidad urgente.',
      coupling: 'Acople operativo con evidencia institucional reciente; señal de arrastre institucional (cobertura mayo-junio), no un match directo NASA/USGS dentro de la semana.',
      couplingEn: 'Operational coupling with recent institutional evidence; an institutional carry-over signal (May-June coverage), not a direct NASA/USGS match inside the week.',
      implication: 'Conflicto e inundación se superponen sobre la misma población e infraestructuras, degradando servicios y capacidad de respuesta. Si las hostilidades y la presión hídrica del Éufrates persisten, la combinación puede elevar la necesidad humanitaria y agravar el desplazamiento interno y la gobernanza local en el noreste.',
      tripolar: 'EE.UU. y actores regionales pesan sobre el noreste por seguridad y recursos; Rusia e Irán por influencia y corredores; la UE y el Sur Global por estabilización, agua y retorno de población.',
      sources: [
        { label: 'UNFPA Syria SitRep', url: 'https://reliefweb.int/report/syrian-arab-republic/unfpa-syria-situation-report-1-may-30-june-2026' },
        { label: 'GEOPÓLEM SENTINEL', url: 'https://mdiaznaranjo-a11y.github.io/geopolem-public-site/data/sentinel/conflict-events.json' },
      ],
    },
    {
      id: 'drc-ebola-ituri',
      rank: 3,
      status: 'en observación',
      statusEn: 'observation',
      priority: 'media',
      priorityEn: 'medium',
      accent: '#22d3ee',
      location: 'R. D. Congo · Ituri y noreste',
      headline: 'DRC: Ébola en Ituri con calor y sequedad anormales sobre zona de conflicto',
      headlineEn: 'DRC: Ebola in Ituri with abnormal heat and dryness over a conflict zone',
      fact: 'El Under-Secretary-General Tom Fletcher (OCHA) emitió el 9 de julio de 2026 una declaración sobre el brote de Ébola centrado en Ituri, con acceso humanitario restringido y servicios débiles. El Global Weather Hazards Summary (FEWS NET / ReliefWeb) para el 9-15 de julio de 2026 señala sequedad anormal en el noreste del país y pronóstico de calor anormal por encima de 35 °C.',
      coupling: 'Acople salud pública-ambiente-conflicto en observación robusta: convergencia institucional de tres capas, no un único evento NASA/USGS confirmado en la ventana.',
      couplingEn: 'Public-health / environment / conflict coupling under robust observation: an institutional convergence of three layers, not a single confirmed NASA/USGS event in the window.',
      implication: 'Conflicto y movilidad forzada elevan el riesgo de propagación del brote, mientras el estrés térmico e hídrico y la debilidad de servicios degradan la respuesta. La contención depende de acceso humanitario y continuidad logística; su deterioro podría acelerar la propagación y ampliar el desplazamiento.',
      tripolar: 'Para EE.UU., China, Rusia, UE y Sur Global, DRC sigue siendo nodo de minerales, corredores humanitarios y capacidad estatal; la capa sanitaria-ambiental añade presión sobre un tablero ya frágil.',
      sources: [
        { label: 'OCHA · Ébola DRC (9 jul)', url: 'https://reliefweb.int/report/democratic-republic-congo/statement-ebola-outbreak-democratic-republic-congo-tom-fletcher-under-secretary-general-humanitarian-affairs-and-emergency-relief-coordinator-9-july-2026' },
        { label: 'FEWS NET · Weather Hazards', url: 'https://reliefweb.int/report/world/global-weather-hazards-summary-july-9-2026-july-15-2026' },
        { label: 'GEOPÓLEM SENTINEL', url: 'https://mdiaznaranjo-a11y.github.io/geopolem-public-site/data/sentinel/conflict-events.json' },
      ],
    },
  ],
  notSelected: {
    location: 'SENTINEL, NASA EONET, USGS',
    label: 'Estado de fuentes · calidad del dato',
    labelEn: 'Source status · data quality',
    note: 'Limitación de la semana: el feed SENTINEL trajo 4 eventos de conflicto (Ucrania, Gaza, Taiwán, Malí) sin fecha ni coordenadas utilizables y de tipo ejemplo (dominio example.org), por lo que el cruce geoespacial automático dio candidate_matches = 0. NASA EONET aportó 67 eventos abiertos y 73 cerrados; USGS entregó 145 sismos M4.5+; ninguno se acopló geoespacialmente a un evento SENTINEL utilizable. Los tres puntos publicados se sostienen con fuentes institucionales humanitarias (IOM/UNHCR, UNFPA, OCHA, FEWS NET), no con el match automático. Se distingue acople operativo de causalidad; no se inventaron correlaciones.',
    source: { label: 'USGS Earthquakes M4.5+', url: 'https://earthquake.usgs.gov/fdsnws/event/1/query?format=geojson&starttime=2026-07-12T22%3A00%3A00Z&endtime=2026-07-19T21%3A59%3A59Z&minmagnitude=4.5&orderby=magnitude' },
  },
  bestShort: {
    title: 'La ruta que el mar no perdona',
    reason: 'Es el acople más nítido de la semana y el único confirmado por fuente institucional humanitaria: conflicto y desplazamiento empujan salidas marítimas hacia una ventana ambiental letal, fuera de temporada y con inundaciones recientes. Acople operativo, sin forzar causalidad.',
    hook: 'Más de 500 personas temidas muertas frente a Myanmar. No es solo el mar: es el conflicto empujando a la gente hacia él.',
    hecho: 'Tras el desplazamiento por conflicto desde Rakhine a finales de junio, una embarcación habría naufragado frente a Ayeyarwady el 8 de julio; IOM y UNHCR temen más de 500 muertos. La travesía fue fuera de temporada, con lluvias torrenciales e inundaciones recientes.',
    evaluacion: 'El conflicto empuja las salidas; el entorno ambiental adverso multiplica la letalidad. Es acople operativo confirmado por fuente institucional, no causalidad del clima sobre el conflicto.',
    hipotesis: 'Mientras el conflicto persista y no haya vías seguras, las salidas marítimas seguirán chocando con ventanas meteorológicas peligrosas: más episodios de alta letalidad en la ruta hacia Cox’s Bazar.',
    close: 'GEOPÓLEM. Bienvenidos al tablero.',
  },
  tags: ['GEOPÓLEM', 'OSINT', 'Geopolítica', 'Inteligencia', 'ClimaYConflicto', 'Rohingya', 'BienvenidosAlTablero'],
  close: 'GEOPÓLEM. Bienvenidos al tablero.',
};

/* ========================================================================
   PLAN Z — Documental de inteligencia GEOPÓLEM
   Petróleo, deuda, poder y rediseño institucional en Venezuela.
   Documental completo alojado en YouTube (público, ~37 min).
   No es una noticia: es una lectura de inteligencia. Método Hecho·Evaluación·Hipótesis.
   ======================================================================== */
export const PLAN_Z = {
  id: 'plan-z',
  slug: 'plan-z',
  category: 'osint',
  tone: 'red',
  eyebrow: 'Documental de inteligencia',
  eyebrowEn: 'Intelligence documentary',
  title: 'PLAN Z',
  subtitle: 'la mina, la libreta y la firma',
  subtitleEn: 'the mine, the ledger and the signature',
  fullTitle: 'PLAN Z: la mina, la libreta y la firma | GEOPÓLEM',
  // Documental completo en YouTube (no se aloja localmente)
  youtube: {
    id: 'SdM8TuhUgvY',
    url: 'https://youtu.be/SdM8TuhUgvY',
    duration: '≈ 37 min',
  },
  // Resumen editorial: qué es y qué no es
  summary: 'Plan Z no es una noticia. Es una lectura de inteligencia sobre petróleo, deuda, poder y rediseño institucional. El documental analiza qué ocurre cuando la arquitectura política, fiscal y diplomática de un Estado depende de un recurso estratégico y ese Estado pierde el control técnico, financiero y operativo sobre él.',
  summaryEn: 'Plan Z is not breaking news. It is an intelligence reading of oil, debt, power and institutional redesign. The documentary examines what happens when a state whose political, fiscal and diplomatic architecture depends on a strategic resource loses technical, financial and operational control over it.',
  notNews: 'Sin amarillismo. Sin propaganda. Sala situacional.',
  notNewsEn: 'No sensationalism. No propaganda. Situation room.',
  // Pregunta analítica central
  question: 'Cuando un petroestado pierde el control sobre su petróleo, ¿quién mueve la palanca energética?',
  questionEn: 'When a petro-state loses control over its oil, who moves the energy lever?',
  questionContext: 'Petróleo. Deuda. Oro. PDVSA. Orinoco. Madrid. Roma. Nueva York.',
  // Disciplinas de inteligencia empleadas
  methods: [
    { id:'osint',  label:'OSINT',  desc:'Fuentes abiertas: documentos, registros y prensa.', descEn:'Open sources: documents, records and press.', accent:'#22d3ee' },
    { id:'humint', label:'HUMINT', desc:'Testimonios y fuentes humanas.', descEn:'Testimonies and human sources.', accent:'#a78bfa' },
    { id:'finint', label:'FININT', desc:'Deuda, acreedores y flujos financieros.', descEn:'Debt, creditors and financial flows.', accent:'#10b981' },
    { id:'geoint', label:'GEOINT', desc:'Mapas, rutas y nodos estratégicos.', descEn:'Maps, routes and strategic nodes.', accent:'#f59e0b' },
  ],
  // Doctrina editorial: Hecho · Evaluación · Hipótesis
  doctrine: [
    { id:'hecho',      label:'Hecho',      labelEn:'Fact',       desc:'Lo verificable en fuentes abiertas.', descEn:'What is verifiable in open sources.' },
    { id:'evaluacion', label:'Evaluación', labelEn:'Assessment', desc:'Lo que las evidencias permiten inferir.', descEn:'What the evidence allows us to infer.' },
    { id:'hipotesis',  label:'Hipótesis',  labelEn:'Hypothesis', desc:'Escenarios plausibles, señalados como tales.', descEn:'Plausible scenarios, flagged as such.' },
  ],
  // Vectores del análisis (chips)
  vectors: ['Petróleo', 'Deuda', 'Oro', 'PDVSA', 'Orinoco', 'Poder', 'Rediseño institucional'],
  // Activación social: copy por plataforma + short 9:16
  social: {
    short: {
      src: './assets/videos/geopolem_plan_z_social_short_30s_9x16.mp4',
      poster: './assets/videos/posters/geopolem_plan_z_social_short_30s_9x16.jpg',
      duration: '00:30',
      label: 'Short · 30s · 9:16',
    },
    summary: {
      src: './assets/videos/geopolem_plan_z_social_summary_9x16.mp4',
      label: 'Resumen · 9:16',
    },
    platforms: [
      { id:'instagram', label:'Instagram', desc:'Reels + Stories', accent:'#ec4899' },
      { id:'tiktok',    label:'TikTok',    desc:'Vertical 9:16',   accent:'#22d3ee' },
      { id:'x',         label:'X',         desc:'Hilo + vídeo',     accent:'#e2e8f0' },
      { id:'linkedin',  label:'LinkedIn',  desc:'Análisis largo',   accent:'#0a66c2' },
      { id:'facebook',  label:'Facebook',  desc:'Reels',            accent:'#1877f2' },
    ],
    caption: 'Plan Z ya está en YouTube. La pregunta no es sólo quién gobierna: es quién mueve la palanca energética. Documental completo en YouTube.',
  },
  // Enlace canónico del documental para los actos de la serie
  seriesUrl: 'https://youtu.be/SdM8TuhUgvY',
  // Orden narrativo de la serie (no mezclar narrativas; preservar secuencia)
  seriesMap: [
    { step: 'I',  key: 'Petróleo / Orinoco',    note: 'La palanca profunda: reserva no equivale a flujo.' },
    { step: 'II', key: 'Petrocaribe',            note: 'Barriles como diplomacia: crédito e influencia.' },
    { step: 'III',key: 'Madrid',                 note: 'Mediación, operadores y zona gris.' },
    { step: 'III bis', key: 'Cuba / Níquel–Cobalto', note: 'Extensión mineral: energía solar y minerales críticos (línea abierta).' },
    { step: 'IV', key: 'Oro / Deuda',            note: 'Cajas alternativas y soberanía informal.' },
    { step: 'V',  key: 'Escenarios',             note: 'Quién captura el flujo futuro.' },
  ],
  // Entregas numeradas de la serie Plan Z (orden de publicación; la #1 abre la serie)
  entregas: [
    {
      n: 1,
      seriesLabel: 'Plan Z · Entrega 01',
      title: '¿Quién mueve el Orinoco?',
      description: 'La primera entrega de Plan Z analiza petróleo, deuda, PDVSA, Orinoco y poder como una arquitectura de flujo energético. No es amarillismo: es inteligencia aplicada al tablero.',
      descriptionEn: 'The first Plan Z release analyses oil, debt, PDVSA, the Orinoco and power as an energy-flow architecture. This is not sensationalism: it is intelligence applied to the board.',
      doctrine: ['hecho', 'evaluacion', 'hipotesis'],
      status: 'Publicado en YouTube',
      statusEn: 'Published on YouTube',
      published: true,
      youtube: 'https://youtu.be/SdM8TuhUgvY',
      cta: 'Ver video completo',
      ctaEn: 'Watch full video',
    },
    {
      n: 2,
      seriesLabel: 'Plan Z · Entrega 02',
      title: 'Cuba entra al tablero: níquel, cobalto y energía solar',
      titleEn: 'Cuba enters the board: nickel, cobalt and solar energy',
      description: 'La segunda entrega desplaza el tablero desde el Orinoco hacia Cuba para analizar una línea abierta de investigación sobre níquel, cobalto, oro y energía solar. No es sentencia: es lectura geoeconómica con fuentes abiertas.',
      descriptionEn: 'The second release shifts the board from the Orinoco towards Cuba to analyse an open line of investigation on nickel, cobalt, gold and solar energy. It is not a verdict: it is a geo-economic reading based on open sources.',
      doctrine: ['hecho', 'evaluacion', 'hipotesis'],
      chips: ['Níquel', 'Cobalto', 'Moa', 'Energía solar', 'OSINT'],
      chipsEn: ['Nickel', 'Cobalt', 'Moa', 'Solar energy', 'OSINT'],
      status: 'Video largo listo · pendiente de enlace público',
      statusEn: 'Long-form video ready · public link pending',
      published: false,
      featured: true,
      cta: 'Próxima publicación',
      ctaEn: 'Upcoming release',
    },
  ],
  // Actos de guion de la serie Plan Z (orden fijo: Orinoco → Petrocaribe → Madrid → Oro/Deuda → Escenarios)
  acts: [
    {
      id: 'acto-ii-orinoco',
      num: 'ACTO II',
      title: 'Orinoco',
      subtitle: '¿Quién mueve la palanca profunda?',
      thesis: 'Venezuela no perdió relevancia por quedarse sin petróleo, sino porque perdió capacidad operativa para convertir reservas en poder efectivo. La Faja del Orinoco es una cadena técnica —crudo extrapesado, diluyentes, mejora, financiamiento, licencias—, no solo una reserva bajo tierra.',
      thesisEn: 'Venezuela did not lose relevance by running out of oil, but by losing the operational capacity to turn reserves into effective power. The Orinoco Belt is a technical chain —extra-heavy crude, diluents, upgrading, financing, licences—, not just an underground reserve.',
      doctrine: 'hipotesis',
      claim: 'Plan Z puede leerse como disputa por la arquitectura del flujo: quién opera, quién financia y quién cobra.',
      visual: 'Mapa de Venezuela con zoom a la Faja del Orinoco; cadena animada yacimiento → diluyente → mejorador → terminal → comprador → deuda.',
      shortTitle: '¿Quién mueve el Orinoco?',
      shortAvailable: true,
    },
    {
      id: 'acto-iii-petrocaribe',
      num: 'ACTO III',
      title: 'Petrocaribe',
      subtitle: 'Barriles como diplomacia',
      thesis: 'Petrocaribe fue la traducción regional del auge petrolero: petróleo caro convertido en crédito barato, crédito barato convertido en influencia, e influencia convertida en alineamientos y margen diplomático. Estructura verificable, no acusación sin expediente.',
      thesisEn: 'Petrocaribe was the regional translation of the oil boom: expensive oil turned into cheap credit, cheap credit into influence, and influence into alignments and diplomatic margin. A verifiable structure, not an accusation without a file.',
      doctrine: 'evaluacion',
      claim: 'La factura petrolera se convirtió en crédito político y relación de dependencia regional.',
      visual: 'Mapa del Caribe con líneas de suministro desde Venezuela; gráfico de precios FOB del crudo venezolano 1999–2012.',
      shortTitle: 'Petrocaribe: barriles como diplomacia',
      shortAvailable: true,
    },
    {
      id: 'acto-iv-madrid',
      num: 'ACTO IV',
      title: 'Madrid',
      subtitle: 'Mediación, operadores y zona gris',
      thesis: 'Madrid no sustituye a Caracas: funciona como interfaz. El tablero deja de ser solo petrolero y pasa a ser jurídico, financiero y político. Se analiza la estructura de acceso —quién intermedia, quién viaja, quién aparece en sociedades— sin afirmar culpabilidad.',
      thesisEn: 'Madrid does not replace Caracas: it works as an interface. The board stops being purely about oil and becomes legal, financial and political. We analyse the structure of access —who mediates, who travels, who appears in companies— without asserting guilt.',
      doctrine: 'hipotesis',
      claim: 'Investigado no equivale a condenado. El hecho procesal se mantiene separado de la lectura estructural.',
      visual: 'Mapa Caracas–Madrid–Nueva York; grafo de nodos de acceso, mediación y radar judicial.',
      shortTitle: 'Madrid: mediación o interfaz',
      shortAvailable: true,
    },
    {
      id: 'acto-iv-bis-cuba',
      num: 'ACTO IV bis',
      title: 'Cuba, níquel y cobalto',
      subtitle: 'La extensión mineral del expediente Madrid',
      thesis: 'Cuba no entra como desvío narrativo, sino como extensión mineral del mismo patrón: energía, sanciones, intermediarios externos y recursos estratégicos. Según medios que citan diligencias de la UDYCO (operación Strongbox) y el sumario del Juzgado de Instrucción nº 46 de Madrid, se investiga un presunto proyecto fotovoltaico de un gigavatio en Cuba con pago en especie mediante níquel, cobalto y oro. El entorno de José Luis Rodríguez Zapatero negó tener información y se distanció de la operación; investigado no equivale a condenado.',
      thesisEn: 'Cuba does not enter as a narrative detour, but as the mineral extension of the same pattern: energy, sanctions, external intermediaries and strategic resources. According to media citing UDYCO proceedings (Operation Strongbox) and the case file of Madrid Investigating Court no. 46, an alleged one-gigawatt photovoltaic project in Cuba is under investigation, with payment in kind through nickel, cobalt and gold. The circle around José Luis Rodríguez Zapatero denied having information and distanced itself from the operation; being investigated is not the same as being convicted.',
      doctrine: 'hipotesis',
      claim: 'Si la línea judicial se confirma, Cuba funcionaría como el espejo mineral del patrón venezolano: recurso estratégico, Estado sancionado, crisis energética e intermediarios externos que disputan quién convierte el recurso en flujo.',
      visual: 'Mapa Madrid–La Habana–Holguín; capa de minerales críticos (níquel, cobalto, oro) y parque solar de un gigavatio; split screen Orinoco / Moa Nickel.',
      shortTitle: 'Cuba entra al tablero: níquel, cobalto y la sombra de Madrid',
      shortAvailable: true,
      disclaimer: 'Línea de investigación abierta, no conclusión judicial. Según medios que citan a la UDYCO. Investigado no equivale a condenado.',
      disclaimerEn: 'Open line of investigation, not a judicial conclusion. According to media citing UDYCO. Being investigated is not being convicted.',
    },
    {
      id: 'acto-v-oro-deuda',
      num: 'ACTO V',
      title: 'Oro y deuda',
      subtitle: 'Soberanía informal',
      thesis: 'Cuando el Estado pierde capacidad para convertir petróleo en flujo estable, busca sustitutos de caja. El oro es caja física, opaca y territorial; la deuda es caja futura, financiera y contractual. Dos caras de un mismo problema de financiamiento.',
      thesisEn: 'When the state loses the capacity to turn oil into stable flow, it seeks cash substitutes. Gold is physical, opaque, territorial cash; debt is future, financial, contractual cash. Two faces of the same financing problem.',
      doctrine: 'evaluacion',
      claim: 'La pregunta no es moral sino estructural: quién controla el activo, quién certifica, quién regula y quién captura el flujo.',
      visual: 'Mapa de Venezuela: petróleo al norte, Arco Minero al sur; capas de oro físico y contratos de deuda.',
      shortTitle: 'Oro y deuda: la soberanía informal',
      shortAvailable: true,
    },
    {
      id: 'acto-vi-escenarios',
      num: 'ACTO VI',
      title: 'Escenarios',
      subtitle: 'Quién captura el flujo futuro',
      thesis: 'El futuro de Venezuela no se decide solo por quién ocupa Miraflores, sino por quién controla la conversión del recurso en flujo. Matriz prospectiva sobre cinco puertas: operativa, regulatoria, contractual, territorial y narrativa.',
      thesisEn: 'Venezuela\'s future is not decided only by who holds Miraflores, but by who controls the conversion of resource into flow. A prospective matrix across five gates: operational, regulatory, contractual, territorial and narrative.',
      doctrine: 'hipotesis',
      claim: 'Capturar el flujo futuro significa controlar quién extrae, quién autoriza, quién renegocia, quién controla el territorio y quién instala la versión pública.',
      visual: 'Mapa con el Orinoco al centro y flechas hacia Washington, Madrid y Nueva York; matriz de escenarios por actor.',
      shortTitle: '¿Quién captura el flujo futuro?',
      shortAvailable: true,
    },
  ],
  tags: ['PlanZ', 'Venezuela', 'Geopolítica', 'Petróleo', 'PDVSA', 'Orinoco', 'OSINT', 'Energía', 'Petropoder', 'Cuba', 'Níquel', 'Cobalto'],
  close: 'GEOPÓLEM. Bienvenidos al tablero.',
};

/* ========================================================================
   GEOPÓLEM · Ficha editorial — Ventaja estratégica
   Marco doctrinal (no coyuntura) basado en Samuel Morales / Global Strategy.
   Estructura de sala situacional: Hecho · Evaluación · Hipótesis + 7 dimensiones.
   ======================================================================== */
export const FICHA_VENTAJA = {
  id: 'ventaja-estrategica',
  slug: 'las-siete-dimensiones-de-la-ventaja-estrategica',
  category: 'estrategia',
  tone: 'cyan',
  eyebrow: 'Ficha editorial · Marco doctrinal',
  eyebrowEn: 'Editorial brief · Doctrinal framework',
  status: 'Ficha editorial · Short listo',
  statusEn: 'Editorial brief · Short ready',
  title: 'Ganará quien aprenda antes',
  titleEn: 'The one who learns first will win',
  subtitle: 'Las siete dimensiones de la ventaja estratégica',
  subtitleEn: 'The seven dimensions of strategic advantage',
  categoryLabel: 'Estrategia · Defensa · Industria',
  categoryLabelEn: 'Strategy · Defence · Industry',
  source: 'Global Strategy · Samuel Morales · 2026',
  sourceUrl: 'https://global-strategy.org/ganara-quien-aprenda-antes-adaptacion-industria-y-las-siete-dimensiones-de-la-ventaja-estrategica/',
  sourceDate: '3 de julio de 2026',
  cover: './assets/geopolem_siete_dimensiones_cover_9x16.jpg',
  coverAlt: 'Portada GEOPÓLEM: Ganará quien aprenda antes, siete dimensiones de la ventaja estratégica.',
  coverRatio: '9:16',
  youtube: {
    id: 'ElGLSWObyoc',
    url: 'https://youtu.be/ElGLSWObyoc',
    label: 'Ver análisis en YouTube',
    labelEn: 'Watch the analysis on YouTube',
  },
  summary: 'Marco doctrinal para leer la guerra contemporánea, la industria de defensa y la competencia tripolar. No es una noticia de coyuntura: es una lectura estratégica sobre quién observa antes, decide antes, produce antes y se regenera antes.',
  summaryEn: 'A doctrinal framework to read contemporary war, the defence industry and tripolar competition. Not breaking news: a strategic reading of who observes, decides, produces and regenerates first.',
  notNews: 'Sin amarillismo. Lectura estratégica. Sala situacional.',
  notNewsEn: 'No sensationalism. Strategic reading. Situation room.',
  // Descripción bilingüe (YouTube Shorts / paquetes de publicación)
  longDescription: [
    'La guerra del siglo XXI no la gana necesariamente quien tiene el arma más avanzada. La ventaja estratégica empieza antes: en la capacidad de observar, aprender, decidir, producir y regenerarse más rápido que el adversario.',
    'A partir del marco publicado por Global Strategy sobre las siete dimensiones de la ventaja estratégica, GEOPÓLEM analiza una idea central: la industria ya no es retaguardia, la narrativa ya no es un adorno y la resiliencia social ya forma parte del campo de batalla.',
    'Ver más rápido. Decidir con claridad. Golpear en el dominio correcto. Resistir con profundidad. Producir más rápido. Narrar con credibilidad. Regenerarse antes.',
    'Este tema encaja directamente con la mirada GEOPÓLEM: inteligencia, defensa, industria, energía y sistema internacional leídos como un solo tablero.',
  ],
  longDescriptionEn: [
    'Twenty-first-century war is not necessarily won by the actor with the most advanced weapon. Strategic advantage begins earlier: in the ability to observe, learn, decide, produce and regenerate faster than the adversary.',
    'Based on the framework published by Global Strategy on the seven dimensions of strategic advantage, GEOPÓLEM analyzes one central idea: industry is no longer just the rear, narrative is no longer decorative, and social resilience is already part of the battlefield.',
    'Seeing faster. Deciding with clarity. Striking in the right domain. Resisting in depth. Producing faster. Narrating with credibility. Regenerating first.',
    'This subject fits directly into the GEOPÓLEM lens: intelligence, defense, industry, energy and the international system read as one single board.',
  ],
  // Doctrina editorial: Hecho · Evaluación · Hipótesis
  doctrine: [
    {
      id: 'hecho',
      label: 'Hecho',
      labelEn: 'Fact',
      body: 'El artículo plantea que la ventaja estratégica contemporánea no depende sólo de poseer plataformas militares avanzadas, sino de aprender, adaptar doctrina, escalar producción y regenerar capacidades antes que el adversario. La tesis central: “la ventaja decisiva no pertenece al actor con la plataforma más avanzada; pertenece al que aprende más rápido”.',
      bodyEn: 'The article argues that contemporary strategic advantage does not depend only on owning advanced military platforms, but on learning, adapting doctrine, scaling production and regenerating capabilities faster than the adversary. The core thesis: decisive advantage belongs not to the actor with the most advanced platform, but to the one who learns fastest.',
    },
    {
      id: 'evaluacion',
      label: 'Evaluación',
      labelEn: 'Assessment',
      body: 'El marco desplaza el análisis desde la superioridad material estática hacia la velocidad de adaptación sistémica. La industria de defensa, la logística, la narrativa estratégica, la resiliencia social y el mando descentralizado forman parte de la guerra, no de su periferia.',
      bodyEn: 'The framework shifts analysis from static material superiority towards the speed of systemic adaptation. The defence industry, logistics, strategic narrative, social resilience and decentralised command are part of the war, not its periphery.',
    },
    {
      id: 'hipotesis',
      label: 'Hipótesis',
      labelEn: 'Hypothesis',
      body: 'En la competencia tripolar, la ventaja no será sólo tecnológica ni presupuestaria: será institucional, industrial y cognitiva. Ganará el bloque que observe antes, decida antes, produzca antes, comunique con credibilidad y se regenere antes. Hipótesis señalada como tal, no como hecho probado.',
      bodyEn: 'In tripolar competition, advantage will not be only technological or budgetary: it will be institutional, industrial and cognitive. The bloc that observes, decides, produces, communicates credibly and regenerates first will win. Flagged as hypothesis, not proven fact.',
    },
  ],
  // Las siete dimensiones de la ventaja estratégica (rejilla visible)
  dimensions: [
    { n: 1, key: 'Ver más rápido',              keyEn: 'See faster',            desc: 'Convertir sensores, OSINT, inteligencia y datos en conocimiento accionable.', descEn: 'Turn sensors, OSINT, intelligence and data into actionable knowledge.' },
    { n: 2, key: 'Decidir con claridad',        keyEn: 'Decide with clarity',   desc: 'Evitar la parálisis burocrática y operar con información incompleta.',        descEn: 'Avoid bureaucratic paralysis and operate with incomplete information.' },
    { n: 3, key: 'Golpear en el dominio correcto', keyEn: 'Strike in the right domain', desc: 'Integrar efectos cinéticos, cibernéticos, informativos, industriales y diplomáticos.', descEn: 'Integrate kinetic, cyber, informational, industrial and diplomatic effects.' },
    { n: 4, key: 'Resistir con profundidad',    keyEn: 'Resist in depth',       desc: 'Proteger infraestructura crítica, logística, sociedad y economía.',            descEn: 'Protect critical infrastructure, logistics, society and economy.' },
    { n: 5, key: 'Producir más rápido',         keyEn: 'Produce faster',        desc: 'Escalar munición, drones, software, repuestos y cadenas críticas.',            descEn: 'Scale munitions, drones, software, spares and critical supply chains.' },
    { n: 6, key: 'Narrar con credibilidad',     keyEn: 'Narrate credibly',      desc: 'Sostener legitimidad pública sin abandonar la verdad operativa.',              descEn: 'Sustain public legitimacy without abandoning operational truth.' },
    { n: 7, key: 'Regenerarse antes',           keyEn: 'Regenerate first',      desc: 'Aprender de pérdidas, corregir doctrina y reconstituir capacidades.',          descEn: 'Learn from losses, correct doctrine and reconstitute capabilities.' },
  ],
  // Línea editorial GEOPÓLEM
  editorialLine: 'La guerra contemporánea no premia sólo al más fuerte. Premia al sistema que aprende antes, produce antes y se regenera antes.',
  editorialLineEn: 'Contemporary war does not reward only the strongest. It rewards the system that learns first, produces first and regenerates first.',
  vectors: ['Estrategia', 'Defensa', 'Industria', 'Tripolaridad', 'OSINT', 'Adaptación', 'Resiliencia'],
  tripolarity: ['EE. UU.', 'China', 'Rusia'],
  tripolarityCenter: 'Velocidad de aprendizaje',
  tripolarityCenterEn: 'Speed of learning',
  tags: ['Estrategia', 'Defensa', 'Industria', 'Tripolaridad', 'OSINT', 'GuerraModerna', 'Ventaja estratégica'],
  close: 'GEOPÓLEM. Bienvenidos al tablero.',
};
