// GEOPÓLEM — Dataset interno de focos (hotspots) y nodos del sistema-mundo
// Fuentes abiertas. Prototipo editorial. No sustituye fuentes oficiales.

export const CATEGORIES = {
  conflicto:   { id:'conflicto',  label:'Conflictos',         color:'#ef4444', icon:'⚔' },
  agua:        { id:'agua',       label:'Agua / Clima',       color:'#22d3ee', icon:'≈' },
  energia:     { id:'energia',    label:'Energía',            color:'#f59e0b', icon:'⚡' },
  ia:          { id:'ia',         label:'IA / Narrativa',     color:'#a78bfa', icon:'◬' },
  migracion:   { id:'migracion',  label:'Migración',          color:'#fb923c', icon:'→' },
  salud:       { id:'salud',      label:'Salud',              color:'#34d399', icon:'+' },
  ddhh:        { id:'ddhh',       label:'Derechos Humanos',   color:'#f472b6', icon:'§' },
  sistema:     { id:'sistema',    label:'Sistema-mundo',      color:'#94a3b8', icon:'◯' },
  chokepoint:  { id:'chokepoint', label:'Chokepoint',         color:'#fbbf24', icon:'⌖' },
  defensa:     { id:'defensa',    label:'Defensa / Rearme',   color:'#f97316', icon:'◆' },
};

export const REGIONS = [
  'Europa del Este','MENA','Sahel','Cuerno de África','Asia del Sur',
  'Asia-Pacífico','América Latina','Norteamérica','Eurasia','Global'
];

// Hotspots editoriales (lat/lng aproximados para placement en mapa equirectangular)
export const FOCOS = [
  {
    id: 'rearme-global',
    title: 'Rearme global — gasto militar récord',
    region: 'Global',
    category: 'defensa',
    intensity: 4,
    coords: { lat: 50.0, lng: 10.0 },
    summary: 'El gasto militar mundial alcanzó 2,887 billones de dólares en 2025, con Europa y Asia-Oceanía como zonas de aceleración y una concentración del 51% en EE.UU., China y Rusia.',
    foda: {
      F: ['Disuasión reforzada', 'Base industrial de defensa en expansión', 'Interoperabilidad OTAN acelerada'],
      O: ['Innovación dual-use', 'Reindustrialización europea', 'Nuevas doctrinas de defensa aérea, drones y ciber'],
      D: ['Presión fiscal', 'Dependencia de proveedores críticos', 'Cuellos de botella en munición y semiconductores'],
      A: ['Carreras armamentísticas regionales', 'Militarización de IA y espacio', 'Riesgo de escalada por error de cálculo'],
    },
    pestel: {
      P: 'Competencia sistémica EE.UU.–China–Rusia, rearme europeo y nuevas alianzas regionales.',
      E: 'Desvío presupuestario hacia defensa, presión fiscal y expansión del complejo militar-industrial.',
      S: 'Debate social entre seguridad, bienestar y fatiga de guerra.',
      T: 'Drones, defensa aérea, munición inteligente, IA militar, espacio y guerra electrónica.',
      A: 'Huella industrial, minerales críticos y energía para cadenas de defensa.',
      L: 'Controles de exportación, sanciones, compras públicas y compromisos OTAN.',
    },
    actores: {
      gobiernos: ['EE.UU.','China','Rusia','miembros OTAN','India','Japón','Corea del Sur','Australia'],
      empresas: ['Lockheed Martin','RTX','Northrop Grumman','Rheinmetall','BAE Systems','Leonardo','Thales'],
      organismos: ['SIPRI','OTAN','UE','ONU','OSCE'],
      armados: ['Fuerzas armadas nacionales','mandos conjuntos','comandos espaciales y ciber'],
      sociedad: ['Industria dual-use','universidades','trabajadores defensa','contribuyentes','ONGs de control armamentístico'],
    },
    risks: [
      { name:'Carrera armamentística Europa–Rusia', prob:0.75, impact:0.85, speed:0.55, contain:0.45 },
      { name:'Choque industrial por munición y defensa aérea', prob:0.7, impact:0.65, speed:0.6, contain:0.55 },
      { name:'Escalada Indo-Pacífico', prob:0.45, impact:0.95, speed:0.75, contain:0.35 },
      { name:'Militarización acelerada de IA', prob:0.8, impact:0.75, speed:0.85, contain:0.25 },
    ],
    scenarios: {
      base:        { title:'Rearme sostenido y gestión de disuasión', señales:['Presupuestos plurianuales','Compras conjuntas UE','Aumento producción munición'], indicadores:['Gasto defensa/PIB','Pedidos defensa aérea','Capacidad 155mm'], impacto:{ agua:1, energia:3, alimentos:1, migracion:1, seguridad:4 } },
      escalada:    { title:'Carrera regional acelerada', señales:['Incidentes Báltico/Mar Negro','Crisis Taiwán','Ciberataques críticos'], indicadores:['Alertas OTAN','Movimientos navales','Contratos urgentes'], impacto:{ agua:1, energia:4, alimentos:2, migracion:2, seguridad:5 } },
      ruptura:     { title:'Conflicto entre grandes potencias', señales:['Cierre rutas marítimas','Ataques a satélites','Movilización parcial'], indicadores:['Brent','seguros marítimos','alertas espacio/ciber'], impacto:{ agua:3, energia:5, alimentos:5, migracion:5, seguridad:5 } },
      desescalada: { title:'Control de armas y compras coordinadas', señales:['Canales militares reabiertos','acuerdos export control','transparencia presupuestaria'], indicadores:['Tratados','reducción incidentes','auditorías gasto'], impacto:{ agua:1, energia:2, alimentos:1, migracion:1, seguridad:2 } },
    },
  },
  {
    id: 'ukr-rus',
    title: 'Ucrania – Rusia',
    region: 'Europa del Este',
    category: 'conflicto',
    intensity: 5,
    coords: { lat: 49.0, lng: 32.0 },
    summary: 'Guerra de desgaste con frente estabilizado, presión sobre infraestructura energética y campañas híbridas (cíber, drones, narrativa).',
    foda: {
      F: ['Apoyo OTAN sostenido', 'Industria de drones ucraniana madura', 'Cohesión política interna UA'],
      O: ['Reconstrucción europea coordinada', 'Integración a cadenas industriales UE', 'Estándares de defensa interoperables'],
      D: ['Demografía y reclutamiento', 'Dependencia de ayuda externa', 'Infraestructura energética golpeada'],
      A: ['Fatiga de aliados', 'Escalada nuclear táctica', 'Sabotaje a cables submarinos'],
    },
    pestel: {
      P: 'Presión electoral en aliados clave; ampliación OTAN.',
      E: 'Costes fiscales de reconstrucción y subsidios energéticos.',
      S: 'Desplazamiento masivo y trauma colectivo.',
      T: 'Guerra de drones, EW, IA en targeting.',
      A: 'Daños ambientales severos (Kakhovka, suelos).',
      L: 'Inmunidad estatal, tribunales especiales, sanciones.',
    },
    actores: {
      gobiernos: ['Ucrania', 'Rusia', 'EE.UU.', 'UE', 'Polonia', 'Turquía'],
      empresas: ['Naftogaz', 'Gazprom', 'Lockheed Martin', 'Rheinmetall'],
      organismos: ['OTAN', 'ONU', 'OSCE', 'CPI'],
      armados: ['FFAA UA', 'FFAA RU', 'Wagner/Africa Corps', 'Brigadas voluntarias'],
      sociedad: ['Diáspora UA', 'ONGs humanitarias', 'OSINT (Bellingcat)'],
    },
    risks: [
      { name: 'Escalada nuclear táctica',   prob: 0.15, impact: 0.95, speed: 0.8, contain: 0.3 },
      { name: 'Colapso red eléctrica UA',   prob: 0.55, impact: 0.7,  speed: 0.6, contain: 0.5 },
      { name: 'Sabotaje cables Báltico',    prob: 0.45, impact: 0.6,  speed: 0.9, contain: 0.4 },
      { name: 'Fatiga apoyo occidental',    prob: 0.6,  impact: 0.75, speed: 0.3, contain: 0.5 },
    ],
    scenarios: {
      base:        { title:'Statu quo de desgaste', señales:['Línea de frente <5km/mes','Apoyo militar estable','Inflación controlada'], indicadores:['Producción 155mm','Tasa drones/día','Sanciones nuevas'], impacto:{ agua:1, energia:3, alimentos:2, migracion:2, seguridad:3 } },
      escalada:    { title:'Apertura de frentes y golpes profundos', señales:['Ataques OTAN-este','Movilización RU','Drones largo alcance'], indicadores:['Lanzamientos misiles/sem','Ciberataques críticos','Cierre espacio aéreo'], impacto:{ agua:2, energia:4, alimentos:3, migracion:4, seguridad:5 } },
      ruptura:     { title:'Uso de arma no convencional o colapso de estado', señales:['Empleo táctico nuclear','Crisis sucesoria Kremlin','Defección masiva'], indicadores:['Alertas IAEA','Movimientos cabezas nucleares','Vacío de mando'], impacto:{ agua:3, energia:5, alimentos:4, migracion:5, seguridad:5 } },
      desescalada: { title:'Alto el fuego negociado, congelado', señales:['Canales Estambul/Doha','Intercambios prisioneros','Pausa ataques infra'], indicadores:['Reuniones técnicas','Comercio cereales','Retorno refugiados'], impacto:{ agua:1, energia:2, alimentos:1, migracion:1, seguridad:2 } },
    },
  },
  {
    id: 'isr-gaza-irn',
    title: 'Israel – Gaza – Irán',
    region: 'MENA',
    category: 'conflicto',
    intensity: 5,
    coords: { lat: 31.5, lng: 34.5 },
    summary: 'Crisis humanitaria en Gaza, frentes con Hezbollah y Houthi, intercambio directo Israel–Irán y riesgo de guerra regional.',
    foda: {
      F: ['Superioridad aérea IL', 'Inteligencia regional', 'Apoyo EE.UU.'],
      O: ['Acuerdos Abraham ampliados', 'Normalización con KSA condicionada'],
      D: ['Coste reputacional global', 'Polarización interna IL', 'Frente norte abierto'],
      A: ['Guerra regional Irán', 'Crisis humanitaria Gaza', 'Bloqueo Bab el-Mandeb'],
    },
    pestel: {
      P: 'Crisis legitimidad de actores, presión CIJ/CPI.',
      E: 'Primas riesgo energético, fletes Mar Rojo.',
      S: 'Trauma generacional, refugiados, antisemitismo/islamofobia.',
      T: 'Iron Dome, drones iraníes Shahed, ciberops.',
      A: 'Agua y agricultura Gaza colapsadas.',
      L: 'Casos genocidio CIJ, órdenes de arresto CPI.',
    },
    actores: {
      gobiernos: ['Israel','EE.UU.','Irán','Egipto','Qatar','Arabia Saudí','Turquía'],
      empresas: ['Elbit','Rafael','NSO','Lockheed','navieras Maersk/MSC'],
      organismos: ['ONU','UNRWA','OIEA','CIJ','CPI','Liga Árabe'],
      armados: ['FDI','Hamás','Hezbollah','Houthis','Cuerpos Quds','PMF Iraq'],
      sociedad: ['ONG humanitarias','Diásporas','Movimientos solidaridad'],
    },
    risks: [
      { name: 'Guerra abierta Israel–Irán',   prob: 0.35, impact: 0.95, speed: 0.85, contain: 0.25 },
      { name: 'Cierre Bab el-Mandeb',         prob: 0.5,  impact: 0.8,  speed: 0.9,  contain: 0.4 },
      { name: 'Frente norte Hezbollah total', prob: 0.4,  impact: 0.85, speed: 0.7,  contain: 0.3 },
      { name: 'Crisis humanitaria irreversible', prob: 0.8, impact: 0.9, speed: 0.5, contain: 0.4 },
    ],
    scenarios: {
      base:        { title:'Contención con escaramuzas', señales:['Mediación Qatar/Egipto','Pausas humanitarias','Intercambios limitados'], indicadores:['Convoyes ayuda/día','Lanzamientos Yemen','Reuniones técnicas'], impacto:{ agua:4, energia:3, alimentos:4, migracion:3, seguridad:4 } },
      escalada:    { title:'Frente norte abierto, golpes Irán', señales:['Movilización norte IL','Ataques bases EE.UU.','Drones Shahed sobre IL'], indicadores:['Cierre aeropuertos','Precios Brent','Evacuaciones'], impacto:{ agua:4, energia:5, alimentos:4, migracion:4, seguridad:5 } },
      ruptura:     { title:'Guerra regional con golpes nucleares no declarados', señales:['Ataque a Natanz/Dimona','Cierre Ormuz','Movilización general'], indicadores:['Brent >$130','Cierre rutas aéreas','Alertas OIEA'], impacto:{ agua:5, energia:5, alimentos:5, migracion:5, seguridad:5 } },
      desescalada: { title:'Alto el fuego sostenido + plan reconstrucción', señales:['Acuerdo rehenes/presos','Apertura cruces','Retiro IDF Gaza'], indicadores:['Convoyes/día','Retorno desplazados','Inversión Golfo'], impacto:{ agua:3, energia:2, alimentos:3, migracion:2, seguridad:3 } },
    },
  },
  {
    id: 'sahel',
    title: 'Sahel — Juntas militares y yihadismo',
    region: 'Sahel',
    category: 'conflicto',
    intensity: 4,
    coords: { lat: 14.5, lng: 0.5 },
    summary: 'Eje Mali–Burkina–Níger consolida AES, salida de Francia/CEDEAO, presencia rusa, expansión yihadista al golfo de Guinea.',
    foda: {
      F: ['Recursos críticos (uranio, oro, litio)','Demografía joven','Soberanía discursiva'],
      O: ['Diversificación de socios (RU/CN/TR)','Renta minera renegociada'],
      D: ['Capacidad estatal débil','Infraestructura deficiente','Economías informales'],
      A: ['Expansión JNIM/EIGS','Sequías y desplazamientos','Ruptura cadenas alimentos'],
    },
    pestel: {
      P:'Juntas militares y narrativa anti-colonial.',
      E:'Renta minera, salida CFA, deuda.',
      S:'Desplazados internos, jóvenes sin futuro.',
      T:'Drones turcos Bayraktar, comms degradadas.',
      A:'Desertificación, lago Chad, agua.',
      L:'Salida CEDEAO, salida CPI parcial.',
    },
    actores: {
      gobiernos:['Mali','Burkina Faso','Níger','Chad','Francia','Rusia','EE.UU.','Turquía','China'],
      empresas:['Orano','Barrick','Wagner/Africa Corps comercial'],
      organismos:['CEDEAO','UA','ONU MINUSMA (terminada)','AES'],
      armados:['FFAA juntas','JNIM','EIGS','Wagner/Africa Corps','milicias étnicas'],
      sociedad:['Diáspora','ONGs','OSC locales','líderes religiosos'],
    },
    risks: [
      { name:'Expansión yihadista a Golfo de Guinea', prob:0.65, impact:0.8, speed:0.6, contain:0.4 },
      { name:'Crisis alimentaria Sahel',              prob:0.7,  impact:0.75,speed:0.5, contain:0.5 },
      { name:'Choque junta vs CEDEAO',                prob:0.4,  impact:0.6, speed:0.7, contain:0.5 },
      { name:'Migración forzada hacia Magreb/UE',     prob:0.75, impact:0.7, speed:0.4, contain:0.4 },
    ],
    scenarios: {
      base:        { title:'AES consolida, frontera Golfo de Guinea presionada', señales:['Acuerdos AES','Wagner permanece','Ataques fronterizos'], indicadores:['Atentados/mes','Tropas RU/junta','Precio uranio'], impacto:{ agua:3, energia:3, alimentos:4, migracion:4, seguridad:4 } },
      escalada:    { title:'Caída de capitales costeras a yihadismo', señales:['Ataques Lomé/Cotonou','Refugiados masivos','Golpes adicionales'], indicadores:['Desplazados/sem','Salida ONGs','Cierre fronteras'], impacto:{ agua:4, energia:4, alimentos:5, migracion:5, seguridad:5 } },
      ruptura:     { title:'Estado fallido en cadena, califato territorial', señales:['Control yihadista capitales','Colapso fiscal','Hambruna declarada'], indicadores:['IPC Phase 5','Éxodo','Intervención externa'], impacto:{ agua:5, energia:4, alimentos:5, migracion:5, seguridad:5 } },
      desescalada: { title:'Pacto político regional + ayuda condicionada', señales:['Elecciones calendarizadas','Mediación regional','Retorno cooperación'], indicadores:['Inversión','Retorno IDPs','Reducción ataques'], impacto:{ agua:2, energia:2, alimentos:3, migracion:3, seguridad:3 } },
    },
  },
  {
    id: 'red-sea',
    title: 'Mar Rojo / Bab el-Mandeb',
    region: 'MENA',
    category: 'chokepoint',
    intensity: 4,
    coords: { lat: 12.5, lng: 43.5 },
    summary: 'Ataques Houthi a navegación reducen tráfico ~50%, fletes y primas suben, desvíos por Cabo de Buena Esperanza añaden 10-14 días.',
    foda: {
      F: ['Misiones EUNAVFOR/Prosperity Guardian','Ruta alternativa Cabo'],
      O: ['Reindustrialización portuaria UE','Diversificación logística'],
      D: ['Coste fletes','Emisiones extra','Vulnerabilidad navieras'],
      A: ['Ataques con misiles balísticos antibuque','Minas','Drones marítimos'],
    },
    pestel: {
      P:'Coalición ad-hoc EE.UU./UE; Yemen-Houthi.',
      E:'Fletes +200-400%, primas seguros marítimos.',
      S:'Encarecimiento bienes, presión inflación.',
      T:'Drones marítimos, balísticos antibuque.',
      A:'Más millas, más emisiones GEI.',
      L:'Derecho marítimo, zonas de exclusión.',
    },
    actores: {
      gobiernos:['EE.UU.','Reino Unido','UE','Egipto','Arabia Saudí','Yemen','Irán','China'],
      empresas:['Maersk','MSC','CMA CGM','Hapag-Lloyd','aseguradoras Lloyd\u2019s'],
      organismos:['ONU','OMI','Autoridad Canal Suez','EUNAVFOR Aspides'],
      armados:['Houthis','CENTCOM','Coalición Aspides'],
      sociedad:['Sindicatos marítimos','ONG ambientales'],
    },
    risks: [
      { name:'Cierre efectivo Bab el-Mandeb',    prob:0.5,  impact:0.85, speed:0.9, contain:0.4 },
      { name:'Daño a buque tanque grande',       prob:0.55, impact:0.7,  speed:0.95,contain:0.5 },
      { name:'Escalada Yemen continental',       prob:0.4,  impact:0.6,  speed:0.6, contain:0.5 },
      { name:'Crisis seguros marítimos',         prob:0.6,  impact:0.65, speed:0.7, contain:0.6 },
    ],
    scenarios: {
      base:        { title:'Ataques esporádicos, desvíos sostenidos', señales:['Convoyes coalición','Ataques semanales','Desvíos parciales'], indicadores:['Tráfico Suez','Fletes Shanghai-Rotterdam','Primas K&R'], impacto:{ agua:1, energia:3, alimentos:3, migracion:2, seguridad:3 } },
      escalada:    { title:'Hundimiento mayor, evacuación rutas', señales:['Tanker hundido','Cierre tránsito','Misiles a EE.UU.'], indicadores:['Brent','Seguro guerra','Cierre puertos'], impacto:{ agua:2, energia:5, alimentos:4, migracion:3, seguridad:4 } },
      ruptura:     { title:'Bloqueo total, choque Irán', señales:['Cierre Ormuz vinculado','Ataques Aramco','Movilización Golfo'], indicadores:['Brent >$130','Racionamiento UE','Crisis logística global'], impacto:{ agua:3, energia:5, alimentos:5, migracion:4, seguridad:5 } },
      desescalada: { title:'Cese hostilidades Yemen + acuerdo regional', señales:['Tregua Yemen','Levantamiento bloqueo','Retorno tráfico'], indicadores:['Tráfico Suez recupera','Fletes caen','Primas normalizan'], impacto:{ agua:1, energia:1, alimentos:1, migracion:1, seguridad:2 } },
    },
  },
  {
    id: 'istanbul',
    title: 'Canal de Estambul / Bósforo',
    region: 'Eurasia',
    category: 'chokepoint',
    intensity: 2,
    coords: { lat: 41.0, lng: 29.0 },
    summary: 'Proyecto canal paralelo TR + Convención de Montreux: cuello de botella crítico para grano y petróleo Mar Negro.',
    foda: {
      F:['Soberanía TR sobre estrechos','Acuerdo grano renovable'],
      O:['Hub logístico Trabzon-Estambul','Mediación TR'],
      D:['Riesgo accidente buques','Tensión Montreux'],
      A:['Sabotaje','Cierre por conflicto Mar Negro'],
    },
    pestel: {
      P:'Equilibrio TR–RU–OTAN.',
      E:'25% del comercio mundial de grano.',
      S:'Estambul: megaciudad y riesgo sísmico.',
      T:'Modernización flota mercante.',
      A:'Riesgo ambiental por densidad de tráfico.',
      L:'Convención de Montreux (1936).',
    },
    actores: {
      gobiernos:['Turquía','Rusia','Ucrania','UE','EE.UU.'],
      empresas:['BOTAŞ','Naftogaz','aseguradoras'],
      organismos:['ONU','OMI'],
      armados:['Marina TR','Flota Mar Negro RU'],
      sociedad:['ONG ambientales Estambul','Sindicatos marítimos'],
    },
    risks: [
      { name:'Suspensión tránsito por conflicto',   prob:0.25, impact:0.85, speed:0.9, contain:0.4 },
      { name:'Accidente grave buque tanque',        prob:0.3,  impact:0.7,  speed:0.95,contain:0.6 },
      { name:'Revisión Montreux por presión OTAN',  prob:0.2,  impact:0.6,  speed:0.3, contain:0.5 },
    ],
    scenarios: {
      base:        { title:'Tráfico normal con monitoreo TR', señales:['Acuerdo grano','Tránsito estable'], indicadores:['Buques/día','Tarifas paso'], impacto:{ agua:1, energia:2, alimentos:3, migracion:1, seguridad:2 } },
      escalada:    { title:'Restricciones por incidente naval RU/UA', señales:['Minas a la deriva','Cierre temporal'], indicadores:['Días cerrado','Cola buques'], impacto:{ agua:1, energia:3, alimentos:4, migracion:1, seguridad:3 } },
      ruptura:     { title:'Cierre indefinido, crisis grano', señales:['Conflicto Mar Negro abierto','Bloqueo Odesa'], indicadores:['Precio trigo CBOT','Crisis MENA/África'], impacto:{ agua:2, energia:4, alimentos:5, migracion:3, seguridad:4 } },
      desescalada: { title:'Acuerdo plurianual de tránsito y grano', señales:['Renovación acuerdo','Seguros estables'], indicadores:['Tráfico normaliza','Precio grano cae'], impacto:{ agua:1, energia:1, alimentos:1, migracion:1, seguridad:1 } },
    },
  },
  {
    id: 'mena-agua',
    title: 'MENA — Estrés hídrico estructural',
    region: 'MENA',
    category: 'agua',
    intensity: 4,
    coords: { lat: 30.0, lng: 38.0 },
    summary: 'Jordán, Eufrates–Tigris, Nilo, acuíferos fósiles agotándose. 12 de 17 países con mayor estrés hídrico del mundo están en MENA.',
    foda: {
      F:['Capital árabe para desalación','Solar abundante'],
      O:['Hidrógeno verde','Reutilización aguas grises'],
      D:['Subsidios distorsionan demanda','Pérdidas de red'],
      A:['Guerras del agua','Migración climática','Fallo cosechas'],
    },
    pestel: {
      P:'Disputas transfronterizas (GERD, Eufrates).',
      E:'Coste desalación, soberanía alimentaria.',
      S:'Éxodo rural, calor extremo.',
      T:'Desalación, drip irrigation, reúso.',
      A:'Sequías multianuales, salinización.',
      L:'Derecho internacional aguas compartidas débil.',
    },
    actores: {
      gobiernos:['Egipto','Etiopía','Sudán','Turquía','Irán','Irak','Siria','Arabia Saudí','Israel','Jordania'],
      empresas:['ACWA Power','Veolia','Suez','IDE Technologies'],
      organismos:['FAO','UN-Water','Banco Mundial','UNESCWA'],
      armados:['No estatales en Mesopotamia','milicias regionales'],
      sociedad:['Movimientos campesinos','jóvenes climáticos'],
    },
    risks: [
      { name:'Día cero capital MENA',                prob:0.4,  impact:0.85, speed:0.4, contain:0.5 },
      { name:'Conflicto agua transfronterizo',       prob:0.45, impact:0.8,  speed:0.5, contain:0.5 },
      { name:'Crisis alimentaria regional',          prob:0.6,  impact:0.8,  speed:0.4, contain:0.5 },
      { name:'Migración climática masiva',           prob:0.7,  impact:0.7,  speed:0.3, contain:0.4 },
    ],
    scenarios: {
      base:        { title:'Deterioro lento + inversión desalación', señales:['Megaproyectos desalación','Subsidios eficiencia'], indicadores:['Capacidad desal/cápita','Pérdidas red','Lluvias'], impacto:{ agua:5, energia:3, alimentos:4, migracion:3, seguridad:3 } },
      escalada:    { title:'Sequía multianual + choque GERD/Eufrates', señales:['Restricciones agua urbana','Cosechas malas','Tensión TR–IQ'], indicadores:['Caudales','Reservas presas','Precios trigo local'], impacto:{ agua:5, energia:3, alimentos:5, migracion:4, seguridad:4 } },
      ruptura:     { title:'Día cero capital + éxodo regional', señales:['Cortes agua urbana','Disturbios','Movilización ejército'], indicadores:['Días sin suministro','IDPs','Importaciones grano'], impacto:{ agua:5, energia:4, alimentos:5, migracion:5, seguridad:5 } },
      desescalada: { title:'Acuerdos cuenca + financiación verde', señales:['Tratados cuenca','Bonos climáticos','Cooperación tech'], indicadores:['Acuerdos firmados','Inversión $/año','Eficiencia uso'], impacto:{ agua:3, energia:2, alimentos:3, migracion:2, seguridad:2 } },
    },
  },
  {
    id: 'asia-agua',
    title: 'Asia del Sur — Glaciares e Indo',
    region: 'Asia del Sur',
    category: 'agua',
    intensity: 4,
    coords: { lat: 30.0, lng: 78.0 },
    summary: 'Retroceso de glaciares HKH alimenta Ganges, Indo, Brahmaputra. Tratado del Indo bajo presión IN–PK. Calor extremo y monzón errático.',
    foda: {
      F:['Tratado Indo (1960) aún vigente','Cooperación científica HKH'],
      O:['Sistemas alerta temprana','Riego eficiente','Reforestación'],
      D:['Sobreexplotación acuíferos','Contaminación industrial','Infra obsoleta'],
      A:['GLOF (desbordes glaciares)','Guerra IN–PK por agua','Inundaciones súbitas'],
    },
    pestel: {
      P:'India–Pakistán; China upstream.',
      E:'Agro 50% empleo regional.',
      S:'700M+ dependen de estos ríos.',
      T:'Sensores remotos, IA hidrológica.',
      A:'Pico de agua en HKH ~2050.',
      L:'Tratado Indo, revisión solicitada por IN.',
    },
    actores: {
      gobiernos:['India','Pakistán','China','Bangladés','Nepal','Bután'],
      empresas:['Hidroeléctricas IN/CN','agrotech'],
      organismos:['ICIMOD','IPCC','Banco Mundial','SAARC'],
      armados:['FFAA IN','FFAA PK'],
      sociedad:['Campesinos','urbanitas Delhi/Karachi','climáticos'],
    },
    risks: [
      { name:'Ruptura Tratado del Indo',            prob:0.3,  impact:0.85, speed:0.6, contain:0.4 },
      { name:'GLOF catastrófica',                   prob:0.45, impact:0.75, speed:0.95,contain:0.3 },
      { name:'Monzón fallido multianual',           prob:0.4,  impact:0.85, speed:0.3, contain:0.4 },
      { name:'Crisis hambruna Pakistán',            prob:0.5,  impact:0.8,  speed:0.4, contain:0.4 },
    ],
    scenarios: {
      base:        { title:'Estrés creciente, acuerdos parciales', señales:['Diálogo técnico IN–PK','Inversión riego'], indicadores:['Caudal Indo','Cosechas','Mortalidad calor'], impacto:{ agua:4, energia:3, alimentos:4, migracion:3, seguridad:3 } },
      escalada:    { title:'IN suspende Tratado, China presiona Brahmaputra', señales:['Notificación IN','Embalses CN','Maniobras militares'], indicadores:['Caudal anómalo','Cosechas PK','Movimientos tropas'], impacto:{ agua:5, energia:3, alimentos:5, migracion:4, seguridad:4 } },
      ruptura:     { title:'Conflicto agua + crisis alimentaria Pakistán', señales:['Choques fronterizos','Disturbios urbanos','Default PK'], indicadores:['Reservas grano PK','IDPs','Conflicto Cachemira'], impacto:{ agua:5, energia:4, alimentos:5, migracion:5, seguridad:5 } },
      desescalada: { title:'Tratado HKH ampliado + inversión clima', señales:['Cooperación HKH','Bonos catástrofe','Reforestación'], indicadores:['Acuerdos','Inversión $/año','Indicadores ambientales'], impacto:{ agua:2, energia:2, alimentos:2, migracion:1, seguridad:1 } },
    },
  },
  {
    id: 'stablecoins',
    title: 'Stablecoins / desinformación financiera',
    region: 'Global',
    category: 'ia',
    intensity: 3,
    coords: { lat: 40.7, lng: -74.0 },
    summary: 'Crecimiento de stablecoins USD-pegged como infraestructura paralela, riesgo de corrida + bots/IA amplificando narrativas de pánico.',
    foda: {
      F:['Liquidez 24/7','Inclusión cross-border'],
      O:['Regulación clara (MiCA, GENIUS Act)','Rieles instituciones'],
      D:['Concentración Tether/Circle','Opacidad reservas'],
      A:['Corrida + desinformación coordinada','Sanciones evadidas'],
    },
    pestel: {
      P:'EE.UU. vs UE vs CN — soberanía monetaria.',
      E:'>$200B en circulación, sistémicamente relevante.',
      S:'Adopción en países de moneda débil.',
      T:'IA generativa amplifica FUD; on-chain forensics.',
      A:'Huella energética (validadores).',
      L:'MiCA UE, GENIUS Act US, FATF.',
    },
    actores: {
      gobiernos:['EE.UU. (OCC/SEC)','UE (ESMA)','China','Singapur','Emiratos'],
      empresas:['Tether','Circle','PayPal','Visa','BlackRock'],
      organismos:['FSB','FATF','BIS','IMF'],
      armados:['Ninguno (riesgo ciber)','OFAC'],
      sociedad:['Cripto-Twitter','medios financieros','DAOs'],
    },
    risks: [
      { name:'Corrida USDT/USDC',                   prob:0.2,  impact:0.9,  speed:0.95,contain:0.4 },
      { name:'Campaña desinformación coordinada',   prob:0.7,  impact:0.6,  speed:0.9, contain:0.5 },
      { name:'Sanción a emisor major',              prob:0.25, impact:0.75, speed:0.7, contain:0.5 },
      { name:'Hackeo masivo bridge',                prob:0.6,  impact:0.55, speed:0.95,contain:0.6 },
    ],
    scenarios: {
      base:        { title:'Crecimiento regulado, dominio USD', señales:['MiCA aplicada','Auditorías reservas','Custodia bancaria'], indicadores:['Capitalización','Volumen','Reservas T-bills'], impacto:{ agua:0, energia:1, alimentos:0, migracion:0, seguridad:2 } },
      escalada:    { title:'Crisis depeg + campaña FUD viral', señales:['Depeg <0.97','Tendencias X coordinadas','Retiros masivos'], indicadores:['Spread on/off','Volumen retiros','Menciones bots'], impacto:{ agua:0, energia:1, alimentos:1, migracion:1, seguridad:3 } },
      ruptura:     { title:'Colapso emisor mayor + contagio cripto/banca', señales:['Bancarrota emisor','Suspensión redenciones','Quiebra exchanges'], indicadores:['Capitalización','BTC drawdown','Bancos expuestos'], impacto:{ agua:0, energia:1, alimentos:1, migracion:2, seguridad:4 } },
      desescalada: { title:'Marco global armonizado + CBDC interoperables', señales:['Acuerdo FSB','Pilotos CBDC','Estándares reservas'], indicadores:['Adopción institucional','Reducción volatilidad'], impacto:{ agua:0, energia:1, alimentos:0, migracion:0, seguridad:1 } },
    },
  },
  {
    id: 'ia-narrativa',
    title: 'IA / Riesgo narrativo global',
    region: 'Global',
    category: 'ia',
    intensity: 4,
    coords: { lat: 37.4, lng: -122.0 },
    summary: 'IA generativa industrializa desinformación: deepfakes electorales, propaganda multilingüe, manipulación de mercados y emocionalización de conflictos.',
    foda: {
      F:['Detección IA mejora','Estándares C2PA','Watermarking'],
      O:['Regulación EU AI Act','Alfabetización mediática','OSINT asistida'],
      D:['Asimetría coste atacante/defensor','Plataformas reducen moderación'],
      A:['Deepfakes en elecciones','Erosión confianza institucional','Bots autónomos'],
    },
    pestel: {
      P:'Elecciones >70 países 2024-25 expuestas.',
      E:'Manipulación de mercados por IA.',
      S:'Polarización, desconfianza generalizada.',
      T:'GenAI multimodal, agentes autónomos.',
      A:'Consumo energético entrenamiento.',
      L:'EU AI Act, DSA, ley anti-deepfake EE.UU.',
    },
    actores: {
      gobiernos:['EE.UU.','UE','China','Reino Unido','India','Brasil'],
      empresas:['OpenAI','Anthropic','Google','Meta','xAI','ByteDance'],
      organismos:['UNESCO','OCDE','GPAI','UN AI Advisory Body'],
      armados:['Cibercomandos','operadores PsyOps','APTs'],
      sociedad:['Verificadores','academia','periodistas','OSINT'],
    },
    risks: [
      { name:'Deepfake decisivo en elección',        prob:0.7,  impact:0.85, speed:0.95,contain:0.4 },
      { name:'Bot-net IA manipulando mercados',      prob:0.5,  impact:0.7,  speed:0.9, contain:0.5 },
      { name:'Colapso confianza fuentes oficiales',  prob:0.65, impact:0.8,  speed:0.4, contain:0.4 },
      { name:'Incidente AGI / capacidad disruptiva', prob:0.15, impact:0.95, speed:0.5, contain:0.2 },
    ],
    scenarios: {
      base:        { title:'Regulación parcial, ataques continuos', señales:['EU AI Act vigente','Sellos C2PA','Detección mejora'], indicadores:['Volumen deepfakes','Tasa detección','Confianza encuestas'], impacto:{ agua:0, energia:2, alimentos:0, migracion:1, seguridad:4 } },
      escalada:    { title:'Crisis electoral por deepfake + manipulación masas', señales:['Deepfake líder','Bots virales','Choques calle'], indicadores:['Engagement bots','Disturbios','Banneos plataformas'], impacto:{ agua:0, energia:2, alimentos:0, migracion:1, seguridad:5 } },
      ruptura:     { title:'Cascada desinformación + incidente IA crítica', señales:['Manipulación bursátil masiva','Apagones info','Pánicos coord.'], indicadores:['Volatilidad VIX','Cortes plataformas','Movilización gobiernos'], impacto:{ agua:0, energia:3, alimentos:1, migracion:2, seguridad:5 } },
      desescalada: { title:'Estándar global C2PA + alfabetización masiva', señales:['Acuerdo G7+G20','Curriculum escolar','Watermarking obligatorio'], indicadores:['Adopción C2PA','Confianza recuperada','Reducción virales'], impacto:{ agua:0, energia:1, alimentos:0, migracion:0, seguridad:2 } },
    },
  },
];

export const SYSTEMA_NODES = [
  { id:'energy',   label:'Energía',      x:0.18, y:0.35, color:'#f59e0b' },
  { id:'food',     label:'Alimentos',    x:0.35, y:0.6,  color:'#84cc16' },
  { id:'water',    label:'Agua',         x:0.5,  y:0.3,  color:'#22d3ee' },
  { id:'trade',    label:'Comercio',     x:0.65, y:0.55, color:'#a78bfa' },
  { id:'data',     label:'Datos / Cables', x:0.8,  y:0.35, color:'#38bdf8' },
  { id:'migration',label:'Migración',    x:0.35, y:0.15, color:'#fb923c' },
  { id:'finance',  label:'Finanzas',     x:0.8,  y:0.7,  color:'#f472b6' },
  { id:'climate',  label:'Clima',        x:0.5,  y:0.85, color:'#34d399' },
];

export const SYSTEMA_LINKS = [
  ['energy','trade'],['energy','food'],['water','food'],['water','energy'],
  ['climate','water'],['climate','migration'],['climate','food'],
  ['trade','finance'],['data','finance'],['data','trade'],
  ['food','migration'],['energy','climate'],['trade','migration'],
  ['water','migration'],['finance','energy'],
];

export const BRIEF_DIARIO = [
  { tema:'defensa',   headline:'SIPRI: gasto militar mundial toca récord histórico', cuerpo:'El tablero entra en fase de rearme estructural: Europa acelera, Asia-Oceanía aumenta y el top 3 concentra más de la mitad del gasto mundial.' },
  { tema:'conflicto', headline:'Ucrania: presión sobre red eléctrica entra en fase invernal', cuerpo:'Drones rusos golpean subestaciones críticas. Apoyo aliado en revisión política tras elecciones. Sin cambio en línea de frente.' },
  { tema:'conflicto', headline:'Gaza: ventana negociadora se estrecha', cuerpo:'Qatar y Egipto mantienen canal abierto pero crece riesgo norte (Hezbollah) y golpes recíprocos Israel–Irán.' },
  { tema:'chokepoint',headline:'Bab el-Mandeb: tráfico Suez sigue 40% por debajo del baseline', cuerpo:'Fletes Shanghai–Rotterdam +180% YoY. Aseguradoras endurecen primas K&R.' },
  { tema:'agua',      headline:'Sahel: ciclo seco prolonga IPC fase 4 en Burkina', cuerpo:'IDPs superan 2.1M. Corredores humanitarios bajo ataque JNIM.' },
  { tema:'energia',   headline:'Europa: almacenamiento gas al 92%, LNG marginal vulnerable', cuerpo:'Choque MENA o frío severo aún pueden empujar TTF arriba de 60 EUR/MWh.' },
  { tema:'ia',        headline:'Deepfakes electorales: pico detección en última semana', cuerpo:'Plataformas reportan +60% take-downs vs trimestre previo. Auditorías C2PA aún voluntarias.' },
  { tema:'migracion', headline:'Mediterráneo central: rutas se reactivan con clima', cuerpo:'Llegadas a Lampedusa repuntan. Túnez–Italia y Libia–Italia siguen siendo corredores principales.' },
  { tema:'salud',     headline:'Mpox clado Ib: expansión sostenida en África central', cuerpo:'OMS mantiene PHEIC. Cobertura vacunal lejos de objetivo. Riesgo de saltos a Europa.' },
  { tema:'ddhh',      headline:'CIJ y CPI: cascada de decisiones técnicas en curso', cuerpo:'Casos Sudáfrica vs Israel y órdenes de arresto siguen tensionando alianzas occidentales.' },
];

export const KPIS = [
  { id:'milex',       label:'Gasto militar mundial', value:'$2.887T', trend:'+2.9%', tone:'orange', sub:'SIPRI 2025' },
  { id:'conflictos',  label:'Conflictos activos',   value:56, trend:'+3', tone:'red',   sub:'monitoreo OSINT' },
  { id:'agua',        label:'Estrés hídrico',       value:'4.0B', trend:'↑', tone:'cyan',  sub:'personas a 2025' },
  { id:'chokepoints', label:'Chokepoints en riesgo',value:7,  trend:'↑', tone:'amber', sub:'sobre 12 críticos' },
  { id:'energia',     label:'Brent referencia',     value:'$83', trend:'±', tone:'amber', sub:'volatilidad alta' },
  { id:'migracion',   label:'Desplazados forzados', value:'120M', trend:'↑', tone:'orange', sub:'ACNUR 2024' },
  { id:'ia',          label:'Deepfakes detectados', value:'+60%', trend:'↑', tone:'violet', sub:'trimestre' },
  { id:'salud',       label:'Emergencias PHEIC',    value:2,  trend:'=', tone:'green', sub:'mpox, polio' },
  { id:'ddhh',        label:'Países en alerta DDHH',value:34, trend:'↑', tone:'pink',  sub:'Freedom House' },
];

export const MILEX = {
  year: 2025,
  sourceName: 'SIPRI Military Expenditure Database / Press Release 2026',
  sourceUrl: 'https://www.sipri.org/media/press-release/2026/global-military-spending-rise-continues-european-and-asian-expenditures-surge',
  databaseUrl: 'https://www.sipri.org/databases/milex',
  global: [
    { label:'Gasto mundial', value:'$2.887T', note:'2,887 billones USD en 2025' },
    { label:'Crecimiento real', value:'+2.9%', note:'vs. 2024' },
    { label:'Carga sobre PIB', value:'2.5%', note:'máximo desde 2009' },
    { label:'Años de aumento', value:'11', note:'aumento consecutivo' },
  ],
  topThree: [
    { country:'Estados Unidos', spending:954, label:'$954B', note:'-7.5% interanual' },
    { country:'China', spending:336, label:'$336B', note:'+7.4% interanual' },
    { country:'Rusia', spending:190, label:'$190B', note:'+5.9% interanual' },
  ],
  concentration: { value:'$1.480T', share:'51%', note:'EE.UU. + China + Rusia' },
  regions: [
    { region:'Europa', spending:864, label:'$864B', growth:'+14%', tone:'red' },
    { region:'Asia y Oceanía', spending:681, label:'$681B', growth:'+8.1%', tone:'amber' },
    { region:'Oriente Medio', spending:218, label:'$218B', growth:'+0.1%', tone:'cyan' },
    { region:'África', spending:58.2, label:'$58.2B', growth:'+8.5%', tone:'orange' },
  ],
  analysis: [
    'El rearme ya no es un fenómeno aislado: funciona como una infraestructura del sistema-mundo que conecta industria, energía, minerales críticos, deuda pública y doctrina militar.',
    'La lectura GEOPÓLEM no es “más gasto equivale a más seguridad”; el punto crítico es dónde se acelera el gasto, qué capacidades se compran y qué señales cruzan el umbral de disuasión a escalada.',
    'Para 2026–2027, la variable decisiva será la capacidad industrial: munición, defensa aérea, drones, sensores, ciber, espacio y resiliencia energética.'
  ],
  watch: ['Compromisos OTAN sobre PIB', 'pedidos de defensa aérea', 'producción 155mm', 'contratos de drones', 'export controls dual-use', 'incidentes Báltico / Mar Negro / Taiwán'],
};

/* ========================================================================
   DOCTRINA GEOPÓLEM — Tripolaridad imperfecta con multipolaridad periférica
   Marco analítico permanente. Conectado a SENTINEL como capa de lectura.
   Vídeo largo + Short teaser referenciados para CTA/embed.
   ======================================================================== */
export const DOCTRINA = {
  id: 'tripolaridad-imperfecta',
  slug: 'tripolaridad-imperfecta',
  category: 'doctrina',
  tone: 'violet',
  eyebrow: 'Doctrina GEOPÓLEM',
  eyebrowEn: 'GEOPÓLEM Doctrine',
  title: 'Tripolaridad imperfecta',
  titleEn: 'Imperfect Tripolarity',
  subtitle: 'con multipolaridad periférica',
  subtitleEn: 'with peripheral multipolarity',
  summary: 'El mundo no es simplemente multipolar. GEOPÓLEM lo lee como una tripolaridad imperfecta con multipolaridad periférica: tres potencias estructuran el tablero, mientras el resto maniobra en sus márgenes.',
  summaryEn: 'The world is not simply multipolar. GEOPÓLEM reads it as an imperfect tripolarity with peripheral multipolarity: three powers structure the board while the rest maneuver at its margins.',
  // La pregunta analítica central de la doctrina
  question: 'La pregunta no es solo cuántos actores existen, sino quién estructura, quién maniobra y quién acelera.',
  questionEn: 'The question is not just how many actors exist, but who structures, who maneuvers, and who accelerates.',
  // Pilares del tablero. role: 'structure' | 'normative' | 'maneuver'
  pillars: [
    {
      id: 'eeuu',
      actor: 'Estados Unidos',
      actorEn: 'United States',
      role: 'structure',
      function: 'Estructura',
      functionEn: 'Structures',
      accent: '#22d3ee',
      domains: ['Alianzas', 'Finanzas', 'Poder militar', 'Sanciones', 'Arquitectura de mando'],
      domainsEn: ['Alliances', 'Finance', 'Military power', 'Sanctions', 'Command architecture'],
    },
    {
      id: 'china',
      actor: 'China',
      actorEn: 'China',
      role: 'structure',
      function: 'Estructura',
      functionEn: 'Structures',
      accent: '#ef4444',
      domains: ['Producción', 'Infraestructura', 'Deuda', 'Tecnología', 'Escala comercial'],
      domainsEn: ['Production', 'Infrastructure', 'Debt', 'Technology', 'Commercial scale'],
    },
    {
      id: 'rusia',
      actor: 'Rusia',
      actorEn: 'Russia',
      role: 'structure',
      function: 'Estructura',
      functionEn: 'Structures',
      accent: '#f59e0b',
      domains: ['Disrupción', 'Energía', 'Presión militar', 'Veto estratégico'],
      domainsEn: ['Disruption', 'Energy', 'Military pressure', 'Strategic veto'],
    },
    {
      id: 'ue',
      actor: 'Unión Europea',
      actorEn: 'European Union',
      role: 'normative',
      function: 'Potencia normativa',
      functionEn: 'Normative power',
      accent: '#a78bfa',
      domains: ['Regulación', 'Estándares', 'Poder normativo'],
      domainsEn: ['Regulation', 'Standards', 'Normative power'],
    },
    {
      id: 'sur-global',
      actor: 'Sur Global',
      actorEn: 'Global South',
      role: 'maneuver',
      function: 'Maniobra y arbitraje',
      functionEn: 'Maneuver & arbitrage',
      accent: '#10b981',
      domains: ['Maniobra', 'Arbitraje', 'Autonomía estratégica', 'Competencia entre potencias'],
      domainsEn: ['Maneuver', 'Arbitrage', 'Strategic autonomy', 'Power competition'],
    },
  ],
  // Ejes de lectura: quién estructura / maniobra / acelera
  axes: [
    { id:'structure', label:'Quién estructura', labelEn:'Who structures', desc:'EE.UU., China y Rusia fijan las reglas, los flujos y los umbrales del tablero.', descEn:'The US, China and Russia set the rules, flows and thresholds of the board.' },
    { id:'maneuver',  label:'Quién maniobra',   labelEn:'Who maneuvers',  desc:'La UE como potencia normativa y el Sur Global arbitran entre potencias para ganar autonomía.', descEn:'The EU as normative power and the Global South arbitrate between powers to gain autonomy.' },
    { id:'accelerate',label:'Quién acelera',    labelEn:'Who accelerates',desc:'La disrupción, la energía y la presión militar aceleran o congelan los ciclos de crisis.', descEn:'Disruption, energy and military pressure accelerate or freeze crisis cycles.' },
  ],
  // Conexión con el feed SENTINEL (no altera los datos, añade capa de lectura)
  sentinel: {
    label: 'Capa de lectura SENTINEL',
    labelEn: 'SENTINEL reading layer',
    note: 'Los eventos de conflicto de SENTINEL se leen con esta doctrina: quién estructura el incidente, quién lo aprovecha para maniobrar y quién lo acelera.',
    noteEn: 'SENTINEL conflict events are read through this doctrine: who structures the incident, who exploits it to maneuver, and who accelerates it.',
  },
  videos: {
    long:  { id:'ii_PIdlupZE', url:'https://www.youtube.com/watch?v=ii_PIdlupZE', label:'Análisis completo', labelEn:'Full analysis' },
    short: { id:'tLni47YWTDw', url:'https://www.youtube.com/watch?v=tLni47YWTDw', label:'Short · teaser', labelEn:'Short · teaser' },
  },
  tags: ['tripolaridad', 'multipolaridad', 'sistema-mundo', 'EE.UU.', 'China', 'Rusia', 'UE', 'Sur Global', 'doctrina'],
  close: 'GEOPÓLEM. Bienvenidos al tablero.',
};

/* ========================================================================
   SENTINEL · Brief semanal de inflexiones conflicto-ambiente
   Capa que cruza el feed SENTINEL/GDELT con NASA EONET, USGS y fuentes
   institucionales. Acoples confirmados vs. en observación.
   Fuente consumible: ./data/sentinel/weekly-brief.json
   IMPORTANTE: correlación temporal no implica causalidad.
   ======================================================================== */
export const SENTINEL_BRIEF = {
  brand: 'GEOPÓLEM',
  eyebrow: 'GEOPÓLEM SENTINEL',
  eyebrowEn: 'GEOPÓLEM SENTINEL',
  title: 'Brief semanal de inflexiones conflicto-ambiente',
  titleEn: 'Weekly conflict-environment inflection brief',
  generatedAt: '2026-06-22T06:10:00Z',
  window: '15–21 de junio de 2026 · Europe/Luxembourg',
  windowEn: 'June 15–21, 2026 · Europe/Luxembourg',
  dataUrl: './data/sentinel/weekly-brief.json',
  summary: 'Se cruzaron eventos del feed SENTINEL/GDELT de GEOPÓLEM con NASA EONET, USGS y fuentes institucionales humanitarias y de seguridad alimentaria. Se detectaron dos acoples confirmados y uno en observación. Ucrania queda como energía estratégica en observación, no seleccionada como acople ambiental directo.',
  summaryEn: 'GEOPÓLEM’s SENTINEL/GDELT feed was cross-referenced with NASA EONET, USGS and institutional humanitarian and food-security sources. Two confirmed couplings and one under observation were detected. Ukraine remains strategic-energy under observation, not selected as a direct environmental coupling.',
  caveat: 'La correlación temporal entre un evento de conflicto y un evento ambiental no implica causalidad.',
  caveatEn: 'Temporal correlation between a conflict event and an environmental event does not imply causation.',
  stats: [
    { label: 'Candidatos de conflicto', labelEn: 'Conflict candidates', value: '4' },
    { label: 'Eventos ambientales revisados', labelEn: 'Environmental events reviewed', value: '31' },
    { label: 'Acoples confirmados', labelEn: 'Confirmed couplings', value: '2' },
    { label: 'En observación', labelEn: 'Under observation', value: '1' },
  ],
  points: [
    {
      id: 'gaza-agua',
      rank: 1,
      status: 'confirmado',
      statusEn: 'confirmed',
      priority: 'alta',
      priorityEn: 'high',
      accent: '#ef4444',
      location: 'Gaza / Israel-Palestina',
      headline: 'Cuando el agua se convierte en línea de control',
      headlineEn: 'When water becomes a line of control',
      fact: 'SENTINEL marcó el 17 de junio de 2026 un evento de alta prioridad sobre un ataque aéreo en Gaza mientras las conversaciones de alto el fuego estaban estancadas. UNICEF reporta ~1,1 millones de niños con incertidumbre diaria sobre el agua, 82% de familias en inseguridad hídrica y caída de la desalación de 20.000 a 16.000 m³/día.',
      coupling: 'Agua, saneamiento, calor estacional y acceso humanitario bajo presión militar y logística.',
      couplingEn: 'Water, sanitation, seasonal heat and humanitarian access under military and logistical pressure.',
      implication: 'El agua deja de ser solo una necesidad civil y se convierte en indicador de control territorial, legitimidad, presión diplomática y riesgo sanitario.',
      tripolar: 'Estados Unidos queda asociado al costo político de sostener a Israel; China puede explotar la narrativa de doble rasero; Rusia usa el teatro como munición discursiva contra Occidente; la UE queda atrapada entre derecho internacional, ayuda y baja capacidad coercitiva.',
      sources: [
        { label: 'GEOPÓLEM SENTINEL', url: 'https://mdiaznaranjo-a11y.github.io/geopolem-public-site/data/sentinel/conflict-events.json' },
        { label: 'UNICEF vía ReliefWeb', url: 'https://reliefweb.int/report/occupied-palestinian-territory/unicef-state-palestine-humanitarian-situation-update-wash-gaza-strip-29-may-2026' },
      ],
    },
    {
      id: 'mali-sahel',
      rank: 2,
      status: 'confirmado',
      statusEn: 'confirmed',
      priority: 'alta',
      priorityEn: 'high',
      accent: '#f59e0b',
      location: 'Mali / Sahel central',
      headline: 'Seguridad, alimentos y clima como arquitectura de fragilidad',
      headlineEn: 'Security, food and climate as an architecture of fragility',
      fact: 'SENTINEL registró el 17 de junio de 2026 nuevas medidas de seguridad anunciadas por la junta en Mali. OCHA reporta 24,3 millones de personas con necesidad humanitaria urgente en el Sahel; la temporada de carestía (jun–ago) podría dejar 15,4 millones en crisis alimentaria o peor. FEWS NET proyecta áreas en Emergencia (IPC Fase 4) hacia diciembre de 2026.',
      coupling: 'Inseguridad, sequía/desertificación, temporada de carestía y presión alimentaria regional.',
      couplingEn: 'Insecurity, drought/desertification, lean season and regional food pressure.',
      implication: 'El acople clima-conflicto no solo agrava el hambre; redefine capacidad estatal, movilidad de grupos armados, desplazamiento y dependencia de ayuda.',
      tripolar: 'Rusia capitaliza vacíos de seguridad; China mira minerales, infraestructura y estabilidad logística; EE.UU. y la UE pierden margen si la cooperación no se traduce en presencia y confianza local; el Sur Global arbitra entre seguridad, desarrollo y soberanía.',
      sources: [
        { label: 'GEOPÓLEM SENTINEL', url: 'https://mdiaznaranjo-a11y.github.io/geopolem-public-site/data/sentinel/conflict-events.json' },
        { label: 'OCHA vía ReliefWeb', url: 'https://reliefweb.int/report/mali/24-million-people-sahel-urgently-need-aid-and-world-needs-do-more' },
        { label: 'FEWS NET', url: 'https://fews.net/global/food-assistance-outlook-brief/june-2026/print' },
      ],
    },
    {
      id: 'taiwan-mekkhala',
      rank: 3,
      status: 'en observación',
      statusEn: 'under observation',
      priority: 'media',
      priorityEn: 'medium',
      accent: '#22d3ee',
      location: 'Taiwán / Mar de Filipinas / Pacífico occidental',
      headline: 'Clima severo en una zona de presión militar',
      headlineEn: 'Severe weather in a zone of military pressure',
      fact: 'SENTINEL registró el 17 de junio de 2026 ejercicios militares chinos cerca de Taiwán. NASA EONET registró el tifón Mekkhala como tormenta severa en el Pacífico occidental (19–21 de junio), con datos asociados al JTWC.',
      coupling: 'Tifón Mekkhala en el entorno del Mar de Filipinas durante la misma ventana semanal.',
      couplingEn: 'Typhoon Mekkhala in the Philippine Sea environment during the same weekly window.',
      implication: 'No hay prueba institucional de interrupción operacional directa; sí existe una señal de observación porque el clima severo puede afectar tempo naval, aéreo, ISR, evacuación y logística regional. No debe presentarse como causalidad confirmada.',
      tripolar: 'China prueba presión de zona gris; EE.UU. y aliados miden respuesta y resiliencia; Rusia observa la distracción estratégica; la UE depende de estabilidad marítima y tecnológica sin ser actor militar central.',
      sources: [
        { label: 'GEOPÓLEM SENTINEL', url: 'https://mdiaznaranjo-a11y.github.io/geopolem-public-site/data/sentinel/conflict-events.json' },
        { label: 'NASA EONET', url: 'https://eonet.gsfc.nasa.gov/api/v3/events?days=7&status=open' },
      ],
    },
  ],
  notSelected: {
    location: 'Ucrania / Rusia',
    label: 'Energía estratégica · en observación',
    labelEn: 'Strategic energy · under observation',
    note: 'Caso crítico por energía y guerra industrial, pero esta semana el vínculo dominante fue energético-industrial, no un evento ambiental directo NASA/USGS. ISW reportó ataques mutuos contra infraestructura energética. Se conserva como capa separada de energía estratégica.',
    source: { label: 'Institute for the Study of War', url: 'https://understandingwar.org/research/russia-ukraine/russian-offensive-campaign-assessment-june-17-2026/' },
  },
  bestShort: {
    title: 'Gaza: cuando el agua se convierte en línea de control',
    reason: 'Combina conflicto, infraestructura de supervivencia, acceso humanitario, legitimidad internacional y lectura tripolar en una narrativa clara para audiencia amplia.',
  },
  tags: ['GEOPÓLEM', 'Geopolítica', 'OSINT', 'Gaza', 'WaterSecurity', 'Sahel', 'Taiwan', 'Tripolaridad', 'BienvenidosAlTablero'],
  close: 'GEOPÓLEM. Bienvenidos al tablero.',
};
