// GEOPÓLEM — Sala audiovisual / Video Intelligence
// Metadata for the curated video library. Files live in ./assets/videos/
// and posters in ./assets/videos/posters/

export const VIDEO_CATEGORIES = {
  manifiesto:   { label: 'Manifiesto',         labelEn: 'Manifesto',          tone: 'cyan',   accent: '#22d3ee' },
  pitch:        { label: 'Pitch institucional', labelEn: 'Institutional pitch', tone: 'cyan',   accent: '#67e8f9' },
  osint:        { label: 'OSINT · Análisis',    labelEn: 'OSINT analysis',     tone: 'red',    accent: '#ef4444' },
  chokepoints:  { label: 'Chokepoints',         labelEn: 'Chokepoints',        tone: 'amber',  accent: '#f59e0b' },
  energia:      { label: 'Energía',             labelEn: 'Energy',             tone: 'amber',  accent: '#fbbf24' },
  infraestructura: { label: 'Infraestructura crítica', labelEn: 'Critical infrastructure', tone: 'amber', accent: '#f59e0b' },
  agua:         { label: 'Agua',                labelEn: 'Water',              tone: 'cyan',   accent: '#22d3ee' },
  finanzas:     { label: 'Finanzas digitales',  labelEn: 'Digital finance',    tone: 'green',  accent: '#10b981' },
  doctrina:     { label: 'Doctrina',            labelEn: 'Doctrine',           tone: 'violet', accent: '#a78bfa' },
  artico:       { label: 'Ártico · Rutas',      labelEn: 'Arctic · Routes',    tone: 'cyan',   accent: '#67e8f9' },
  drones:       { label: 'Guerra de drones',    labelEn: 'Drone warfare',      tone: 'red',    accent: '#fb7185' },
  tripolar:     { label: 'Orden tripolar',      labelEn: 'Tripolar order',     tone: 'violet', accent: '#c4b5fd' },
  hemisferio:   { label: 'OSINT · Hemisferio',   labelEn: 'OSINT · Hemisphere', tone: 'red',    accent: '#f87171' },
};

// Each entry:
//   id          — kebab-case stable id (used as slug)
//   src         — relative path under ./assets/videos
//   poster      — relative poster path
//   title       — short editorial title (display)
//   category    — one of VIDEO_CATEGORIES keys
//   language    — primary audio language code
//   subtitles   — array of subtitle language codes
//   duration    — approximate runtime (display only)
//   description — short editorial summary (ES)
//   strategic   — strategic angle / why it matters
//   tags        — optional array of editorial tags (ES)
//   source      — original filename for traceability
//   featured    — boolean, promoted in the hero strip
//   orientation — 'vertical' (9:16 reels) or 'horizontal'
//   copyShort   — optional short card copy (ES) shown in the player
//   sources     — optional array of { label, url } open-source references
//   editorialClose — optional editorial sign-off line shown in the player
export const VIDEOS = [
  {
    id: 'manifiesto-inaugural',
    src: './assets/videos/geopolem_video_inaugural_es_sub_en_premium.mp4',
    poster: './assets/videos/posters/geopolem_video_inaugural_es_sub_en_premium.jpg',
    title: 'Manifiesto inaugural GEOPÓLEM',
    category: 'manifiesto',
    language: 'ES',
    subtitles: ['EN'],
    duration: '01:30',
    description: 'Vídeo inaugural de la sala situacional GEOPÓLEM: bienvenida al tablero, doctrina editorial y propósito OSINT.',
    strategic: 'Define la voz de marca y el marco geopolítico bajo el que se interpretan todos los focos.',
    source: 'geopolem_video_inaugural_es_sub_en_premium.mp4',
    featured: true,
    orientation: 'horizontal',
  },
  {
    id: 'pitch-sala-situacional',
    src: './assets/videos/geopolem_pitch_video_sala_situacional.mp4',
    poster: './assets/videos/posters/geopolem_pitch_video_sala_situacional.jpg',
    title: 'Pitch · Sala situacional editorial',
    category: 'pitch',
    language: 'ES',
    subtitles: [],
    duration: '00:45',
    description: 'Pitch institucional en español: GEOPÓLEM como sala situacional editorial para lectores estratégicos.',
    strategic: 'Mensaje para aliados editoriales, inversores y partners institucionales.',
    source: 'geopolem_pitch_video_sala_situacional.mp4',
    featured: true,
    orientation: 'horizontal',
  },
  {
    id: 'pitch-english',
    src: './assets/videos/geopolem_pitch_video_english_subtitles.mp4',
    poster: './assets/videos/posters/geopolem_pitch_video_english_subtitles.jpg',
    title: 'Pitch · Editorial situation room (EN)',
    category: 'pitch',
    language: 'ES',
    subtitles: ['EN'],
    duration: '00:45',
    description: 'Versión con subtítulos en inglés del pitch institucional GEOPÓLEM, pensada para audiencias internacionales.',
    strategic: 'Apertura a alianzas con outlets y think tanks en mercados anglófonos.',
    source: 'geopolem_pitch_video_english_subtitles.mp4',
    featured: false,
    orientation: 'horizontal',
  },
  {
    id: 'reel-drones',
    src: './assets/videos/geopolem_reel_drones_en_subtitles.mp4',
    poster: './assets/videos/posters/geopolem_reel_drones_en_subtitles.jpg',
    title: 'Reel · Guerra de drones',
    category: 'drones',
    language: 'ES',
    subtitles: ['EN'],
    duration: '00:30',
    description: 'Reel vertical sobre la transformación del campo de batalla por los enjambres de drones FPV y la doctrina anti-drone.',
    strategic: 'Cambio doctrinal: la guerra híbrida ya no se mide solo en blindados, sino en operadores remotos y guerra electrónica.',
    source: 'geopolem_reel_drones_en_subtitles.mp4',
    featured: true,
    orientation: 'vertical',
  },
  {
    id: 'canal-estambul',
    src: './assets/videos/geopolem_canal_estambul_reel_es.mp4',
    poster: './assets/videos/posters/geopolem_canal_estambul_reel_es.jpg',
    title: 'Canal de Estambul · Geopolítica del Bósforo',
    category: 'chokepoints',
    language: 'ES',
    subtitles: [],
    duration: '00:40',
    description: 'Reel sobre el Canal de Estambul: ¿alternativa al Bósforo o palanca geopolítica para reescribir Montreux?',
    strategic: 'Si Turquía controla un canal paralelo, redefine el régimen de paso para la flota rusa del Mar Negro.',
    source: 'geopolem_canal_estambul_reel_es.mp4',
    featured: false,
    orientation: 'vertical',
  },
  {
    id: 'turquia-siguiente',
    src: './assets/videos/geopolem_turquia_siguiente_reel_es.mp4',
    poster: './assets/videos/posters/geopolem_turquia_siguiente_reel_es.jpg',
    title: 'Turquía, la siguiente potencia bisagra',
    category: 'doctrina',
    language: 'ES',
    subtitles: [],
    duration: '00:35',
    description: 'Reel editorial: por qué Turquía es el actor bisagra entre OTAN, BRICS+ y el corredor euroasiático.',
    strategic: 'Ankara como árbitro entre bloques: drones, gas, granos y rutas. Vigilar antes que reaccionar.',
    source: 'geopolem_turquia_siguiente_reel_es.mp4',
    featured: false,
    orientation: 'vertical',
  },
  {
    id: 'stablecoins',
    src: './assets/videos/geopolem_stablecoins_reel_geopolem.mp4',
    poster: './assets/videos/posters/geopolem_stablecoins_reel_geopolem.jpg',
    title: 'Stablecoins · Dolarización digital',
    category: 'finanzas',
    language: 'ES',
    subtitles: [],
    duration: '00:45',
    description: 'Reel sobre stablecoins, dolarización digital y la nueva arquitectura del eurodólar tokenizado.',
    strategic: 'El dólar se extiende vía stablecoins privadas; los Estados pierden monopolio monetario sin disparar un tiro.',
    source: 'geopolem_stablecoins_reel_geopolem.mp4',
    featured: false,
    orientation: 'vertical',
  },
  {
    id: 'water-crisis',
    src: './assets/videos/geopolem_water_crisis_reel_es.mp4',
    poster: './assets/videos/posters/geopolem_water_crisis_reel_es.jpg',
    title: 'Crisis global del agua',
    category: 'agua',
    language: 'ES',
    subtitles: [],
    duration: '00:50',
    description: 'Reel sobre la crisis hídrica global: acuíferos en colapso, presas geopolíticas y el agua como nuevo activo estratégico.',
    strategic: 'El agua es la próxima frontera de conflicto: del Nilo al Indo, del Tigris al Colorado.',
    source: 'geopolem_water_crisis_reel_es.mp4',
    featured: false,
    orientation: 'vertical',
  },
  {
    id: 'artico-osint',
    src: './assets/videos/geopolem_reel_artico_osint_es_sub_en_final.mp4',
    poster: './assets/videos/posters/geopolem_reel_artico_osint_es_sub_en_final.jpg',
    title: 'Ártico · OSINT del deshielo',
    category: 'artico',
    language: 'ES',
    subtitles: ['EN'],
    duration: '00:45',
    description: 'Análisis OSINT del Ártico: bases rusas, despliegues OTAN y el deshielo que abre la Ruta del Norte.',
    strategic: 'El Ártico deja de ser periferia y se convierte en teatro central de competencia entre EEUU, Rusia y China.',
    source: 'geopolem_reel_artico_osint_es_sub_en_final.mp4',
    featured: true,
    orientation: 'vertical',
  },
  {
    id: 'artico-rutas',
    src: './assets/videos/geopolem_reel_artico_guerra_rutas_es_sub_en.mp4',
    poster: './assets/videos/posters/geopolem_reel_artico_guerra_rutas_es_sub_en.jpg',
    title: 'Ártico · Guerra de rutas',
    category: 'artico',
    language: 'ES',
    subtitles: ['EN'],
    duration: '00:50',
    description: 'Reel sobre la pugna por las rutas marítimas árticas: NSR rusa, Northwest Passage y la Polar Silk Road china.',
    strategic: 'Quien controla la ruta polar acorta la geografía global y reescribe el coste de la energía y el comercio.',
    source: 'geopolem_reel_artico_guerra_rutas_es_sub_en.mp4',
    featured: false,
    orientation: 'vertical',
  },
  {
    id: 'hormuz-chokepoint',
    src: './assets/videos/geopolem_reel_hormuz_chokepoint_digital_es_sub_en.mp4',
    poster: './assets/videos/posters/geopolem_reel_hormuz_chokepoint_digital_es_sub_en.jpg',
    title: 'Hormuz · Chokepoint digital',
    category: 'chokepoints',
    language: 'ES',
    subtitles: ['EN'],
    duration: '01:10',
    description: 'Reel sobre el estrecho de Ormuz como chokepoint físico y digital: GPS spoofing, ciberataques y guerra cognitiva.',
    strategic: 'El estrangulamiento ya no es solo naval: cables, sensores y narrativas también pueden cortarse.',
    source: 'geopolem_reel_hormuz_chokepoint_digital_es_sub_en.mp4',
    featured: true,
    orientation: 'vertical',
  },
  {
    id: 'mundo-tripolar',
    src: './assets/videos/geopolem_reel_mundo_tripolar_es_sub_en.mp4',
    poster: './assets/videos/posters/geopolem_reel_mundo_tripolar_es_sub_en.jpg',
    title: 'Mundo tripolar',
    category: 'tripolar',
    language: 'ES',
    subtitles: ['EN'],
    duration: '00:55',
    description: 'Reel editorial: el fin del unipolarismo y la consolidación de un orden tripolar EEUU–China–coalición intermedia.',
    strategic: 'El sistema-mundo se está rearmando alrededor de tres polos. Pensar en bilateral es ya pensar en obsoleto.',
    source: 'geopolem_reel_mundo_tripolar_es_sub_en.mp4',
    featured: true,
    orientation: 'vertical',
  },
  {
    id: 'osint-venezuela',
    src: './assets/videos/geopolem_reel_osint_trump_venezuela_es_sub_en.mp4',
    poster: './assets/videos/posters/geopolem_reel_osint_trump_venezuela_es_sub_en.jpg',
    title: 'OSINT · Trump–Venezuela',
    category: 'osint',
    language: 'ES',
    subtitles: ['EN'],
    duration: '00:50',
    description: 'OSINT sobre la doctrina Trump 2.0 hacia Venezuela: presión naval en el Caribe, petróleo y migración.',
    strategic: 'Venezuela es laboratorio de la nueva política exterior estadounidense: coerción híbrida sin guerra abierta.',
    source: 'geopolem_reel_osint_trump_venezuela_es_sub_en.mp4',
    featured: false,
    orientation: 'vertical',
  },
  {
    id: 'mearsheimer-mathews',
    src: './assets/videos/geopolem_reel_mearsheimer_mathews_es_sub_en.mp4',
    poster: './assets/videos/posters/geopolem_reel_mearsheimer_mathews_es_sub_en.jpg',
    title: 'Mearsheimer vs Mathews',
    category: 'doctrina',
    language: 'ES',
    subtitles: ['EN'],
    duration: '01:00',
    description: 'Reel doctrinal: realismo ofensivo de Mearsheimer frente al institucionalismo de Mathews ante la crisis del orden liberal.',
    strategic: 'Marco mental para leer Ucrania, Taiwán y Oriente Medio sin caer en el reduccionismo ideológico.',
    source: 'geopolem_reel_mearsheimer_mathews_es_sub_en.mp4',
    featured: false,
    orientation: 'vertical',
  },
  {
    id: 'otan-retiro-eeuu',
    src: './assets/videos/geopolem_reel_osint_otan_retiro_eeuu_es_sub_en_final.mp4',
    poster: './assets/videos/posters/geopolem_reel_osint_otan_retiro_eeuu_es_sub_en_final.jpg',
    title: 'OSINT · OTAN sin EEUU',
    category: 'osint',
    language: 'ES',
    subtitles: ['EN'],
    duration: '01:00',
    description: 'OSINT sobre el escenario de retirada estadounidense de la OTAN: brechas de mando, paraguas nuclear y rearme europeo.',
    strategic: 'Si EEUU pivota a Indo-Pacífico, Europa hereda su propia defensa: ¿con qué doctrina y qué presupuesto?',
    source: 'geopolem_reel_osint_otan_retiro_eeuu_es_sub_en_final.mp4',
    featured: true,
    orientation: 'vertical',
  },
  {
    id: 'otan-retiro-30s',
    src: './assets/videos/geopolem_reel_osint_otan_retiro_eeuu_30s_es_sub_en.mp4',
    poster: './assets/videos/posters/geopolem_reel_osint_otan_retiro_eeuu_30s_es_sub_en.jpg',
    title: 'OSINT · OTAN sin EEUU · 30s',
    category: 'osint',
    language: 'ES',
    subtitles: ['EN'],
    duration: '00:30',
    description: 'Versión corta (30s) del briefing OSINT sobre la posible retirada estadounidense de la OTAN.',
    strategic: 'Formato corto para redes verticales: el mismo argumento, comprimido a alto impacto.',
    source: 'geopolem_reel_osint_otan_retiro_eeuu_30s_es_sub_en.mp4',
    featured: false,
    orientation: 'vertical',
  },
  {
    id: 'opep-fragmentacion',
    src: './assets/videos/geopolem_reel_opep_fragmentacion_es_sub_en.mp4',
    poster: './assets/videos/posters/geopolem_reel_opep_fragmentacion_es_sub_en.jpg',
    title: 'OPEP · Fragmentación energética',
    category: 'energia',
    language: 'ES',
    subtitles: ['EN'],
    duration: '00:45',
    description: 'Reel sobre la fragmentación interna de la OPEP+: tensiones Riad–Moscú, cuotas, dolarización y demanda china.',
    strategic: 'El cartel ya no fija precio; lo negocia en un tablero multipolar donde China e India son los nuevos árbitros.',
    source: 'geopolem_reel_opep_fragmentacion_es_sub_en.mp4',
    featured: false,
    orientation: 'vertical',
  },
  {
    id: 'venezuela-sistema-electrico',
    src: './assets/videos/geopolem_reel_venezuela_sistema_electrico_es_sub_en.mp4',
    poster: './assets/videos/posters/geopolem_reel_venezuela_sistema_electrico_es_sub_en.jpg',
    title: 'Venezuela: sistema eléctrico bajo estrés',
    category: 'infraestructura',
    language: 'ES',
    subtitles: ['EN'],
    duration: '02:38',
    description: 'No son solo apagones: es una arquitectura eléctrica bajo estrés. Generación centralizada, fuerte dependencia hidroeléctrica, transmisión exigida, respaldo térmico regional insuficiente y operación al límite.',
    strategic: 'Venezuela muestra cómo la falla de una red puede convertirse en variable geopolítica: energía, petróleo, agua, frontera, migración e inversión entran en el mismo tablero.',
    copyShort: 'No son solo apagones. Es una arquitectura eléctrica bajo estrés. Venezuela muestra cómo la falla de una red puede convertirse en variable geopolítica: energía, petróleo, agua, frontera, migración e inversión entran en el mismo tablero.',
    sources: [
      { label: 'U.S. Energy Information Administration · Venezuela', url: 'https://www.eia.gov/international/content/analysis/countries_long/Venezuela/' },
      { label: 'EFE · Rationing nightmare of a Venezuela desperate to recover its power grid', url: 'https://efe.com/english/economy/2026-05-09/rationing-nightmare-of-a-venezuela-desperate-to-recover-its-power-grid/' },
    ],
    editorialClose: 'GEOPÓLEM. Bienvenidos al tablero.',
    tags: ['Venezuela', 'Energía', 'Infraestructura crítica', 'OSINT', 'Geopolítica'],
    source: 'geopolem_reel_venezuela_sistema_electrico_es_sub_en.mp4',
    featured: true,
    orientation: 'vertical',
  },
  {
    id: 'cuba-tablero',
    src: './assets/videos/geopolem_reel_cuba_tablero_es_sub_en_v2.mp4',
    poster: './assets/videos/posters/geopolem_reel_cuba_tablero_es_sub_en_v2.jpg',
    title: 'Cuba vuelve al tablero',
    category: 'hemisferio',
    language: 'ES',
    subtitles: ['EN'],
    duration: '01:20',
    description: 'Hipótesis estratégica sobre Cuba como punto de presión hemisférica: no invasión como escenario base, sino coerción, sanciones, cerco financiero, inteligencia, presión migratoria y desgaste interno.',
    strategic: 'Mira la arquitectura de presión: energía, remesas, puertos, diáspora, legitimidad e inteligencia.',
    tags: ['Cuba', 'Estados Unidos', 'OSINT', 'Guerra híbrida', 'Seguridad hemisférica'],
    source: 'geopolem_reel_cuba_tablero_es_sub_en_v2.mp4',
    featured: true,
    orientation: 'vertical',
  },
  {
    id: 'trampa-tucidides-tripolaridad',
    src: './assets/videos/geopolem_reel_trampa_tucidides_tripolaridad_es_sub_en.mp4',
    poster: './assets/videos/posters/geopolem_reel_trampa_tucidides_tripolaridad_es_sub_en.jpg',
    title: 'Trampa de Tucídides y tripolaridad',
    category: 'tripolar',
    language: 'ES',
    subtitles: ['EN'],
    duration: '02:30',
    description: 'La trampa de Tucídides suele contarse como un duelo entre la potencia dominante y la ascendente. Pero el tablero actual no es bilateral: es un triángulo de presión entre EEUU, China y Rusia donde Ucrania, Taiwán, el Ártico, el Mar Negro, el Golfo Pérsico y los chokepoints marítimos son placas del mismo sistema.',
    strategic: 'EEUU conserva alianzas, dólar, mares y arquitectura militar global; China concentra escala industrial, tecnología y presión sobre el Indo-Pacífico; Rusia altera el sistema con energía, capacidad nuclear, profundidad territorial y guerra híbrida. La trampa ya no es una línea recta.',
    copyShort: 'La trampa de Tucídides ya no es una línea recta entre dos potencias: es un triángulo de presión EEUU–China–Rusia. No mires solo el titular; lee la arquitectura de presión.',
    sources: [
      { label: 'Harvard Kennedy School · Graham Allison y la trampa de Tucídides', url: 'https://www.belfercenter.org/thucydides-trap/overview-thucydides-trap' },
      { label: 'SIPRI Yearbook 2025 · Riesgos nucleares y arsenales', url: 'https://www.sipri.org/yearbook/2025' },
      { label: 'IMF · World Economic Outlook', url: 'https://www.imf.org/en/Publications/WEO' },
      { label: 'World Bank · Military expenditure (% of GDP)', url: 'https://data.worldbank.org/indicator/MS.MIL.XPND.GD.ZS' },
    ],
    editorialClose: 'GEOPÓLEM. Bienvenidos al tablero.',
    tags: ['Tripolaridad', 'Trampa de Tucídides', 'Estados Unidos', 'China', 'Rusia', 'Sistema internacional', 'Seguridad global', 'OSINT'],
    source: 'geopolem_reel_trampa_tucidides_tripolaridad_es_sub_en.mp4',
    featured: true,
    orientation: 'vertical',
  },
  {
    id: 'rehemisferizacion-presion-hemisferica',
    src: './assets/videos/geopolem_reel_rehemisferizacion_presion_hemisferica_es_sub_en.mp4',
    poster: './assets/videos/posters/geopolem_reel_rehemisferizacion_presion_hemisferica_es_sub_en.jpg',
    title: 'Re-hemisphering · Arquitectura de presión hemisférica',
    category: 'hemisferio',
    language: 'ES',
    subtitles: ['EN'],
    duration: '02:23',
    description: 'No es conspiración pura. Tampoco es prueba total. Es arquitectura de presión hemisférica. Project 2025 sí habla de re-hemisphering —manufactura, energía y cadenas productivas reorientadas hacia el hemisferio occidental—, pero eso no equivale a una orden explícita de control absoluto desde Groenlandia hasta Venezuela.',
    strategic: 'La capa seria está en la doctrina: Monroe reactivada y Trump Corollary, con Groenlandia (Ártico, radar, minerales), Panamá (paso marítimo) y Venezuela (petróleo, Caribe, migración y presión sobre potencias externas) como piezas de una misma arquitectura de presión.',
    copyShort: 'No es conspiración pura. Tampoco es prueba total. Es arquitectura de presión hemisférica. GEOPÓLEM no compra propaganda: la disecciona. Lee la arquitectura —Monroe reactivada, Groenlandia, Panamá, Venezuela— sin confundir un patrón con un plan total.',
    sources: [
      { label: 'The Heritage Foundation · Project 2025 — Mandate for Leadership', url: 'https://www.project2025.org/policy/' },
      { label: 'The White House', url: 'https://www.whitehouse.gov/' },
      { label: 'U.S. Department of Defense', url: 'https://www.defense.gov/' },
      { label: 'U.S. Department of Justice', url: 'https://www.justice.gov/' },
    ],
    editorialClose: 'GEOPÓLEM. Bienvenidos al tablero.',
    tags: ['Re-hemisphering', 'Doctrina Monroe', 'Project 2025', 'Groenlandia', 'Panamá', 'Venezuela', 'Caribe', 'OSINT', 'Seguridad hemisférica'],
    source: 'geopolem_reel_rehemisferizacion_presion_hemisferica_es_sub_en.mp4',
    featured: true,
    orientation: 'vertical',
  },
];

export const VIDEO_TOTAL_COUNT = VIDEOS.length;
