// GEOPÓLEM — Sala audiovisual / Video Intelligence
// Metadata for the curated video library. Files live in ./assets/videos/
// and posters in ./assets/videos/posters/

export const VIDEO_CATEGORIES = {
  manifiesto:   { label: 'Manifiesto',         labelEn: 'Manifesto',          tone: 'cyan',   accent: '#22d3ee' },
  pitch:        { label: 'Pitch institucional', labelEn: 'Institutional pitch', tone: 'cyan',   accent: '#67e8f9' },
  osint:        { label: 'OSINT · Análisis',    labelEn: 'OSINT analysis',     tone: 'red',    accent: '#ef4444' },
  chokepoints:  { label: 'Chokepoints',         labelEn: 'Chokepoints',        tone: 'amber',  accent: '#f59e0b' },
  energia:      { label: 'Energía',             labelEn: 'Energy',             tone: 'amber',  accent: '#fbbf24' },
  agua:         { label: 'Agua',                labelEn: 'Water',              tone: 'cyan',   accent: '#22d3ee' },
  finanzas:     { label: 'Finanzas digitales',  labelEn: 'Digital finance',    tone: 'green',  accent: '#10b981' },
  doctrina:     { label: 'Doctrina',            labelEn: 'Doctrine',           tone: 'violet', accent: '#a78bfa' },
  artico:       { label: 'Ártico · Rutas',      labelEn: 'Arctic · Routes',    tone: 'cyan',   accent: '#67e8f9' },
  drones:       { label: 'Guerra de drones',    labelEn: 'Drone warfare',      tone: 'red',    accent: '#fb7185' },
  tripolar:     { label: 'Orden tripolar',      labelEn: 'Tripolar order',     tone: 'violet', accent: '#c4b5fd' },
};

// Each entry:
//   id          — kebab-case stable id (used as slug)
//   src         — relative path under ./assets/videos
//   poster      — relative poster path
//   title       — short editorial title (display)
//   category    — one of VIDEO_CATEGORIES keys
//   language    — primary audio language code
//   subtitles   — array of subtitle language codes
//   duration    — approximate runtime (display only)
//   description — short editorial summary (ES)
//   strategic   — strategic angle / why it matters
//   source      — original filename for traceability
//   featured    — boolean, promoted in the hero strip
//   orientation — 'vertical' (9:16 reels) or 'horizontal'
export const VIDEOS = [
  {
    id: 'manifiesto-inaugural',
    src: './assets/videos/geopolem_video_inaugural_es_sub_en_premium.mp4',
    poster: './assets/videos/posters/geopolem_video_inaugural_es_sub_en_premium.jpg',
    title: 'Manifiesto inaugural GEOPÓLEM',
    category: 'manifiesto',
    language: 'ES',
    subtitles: ['EN'],
    duration: '01:30',
    description: 'Vídeo inaugural de la sala situacional GEOPÓLEM: bienvenida al tablero, doctrina editorial y propósito OSINT.',
    strategic: 'Define la voz de marca y el marco geopolítico bajo el que se interpretan todos los focos.',
    source: 'geopolem_video_inaugural_es_sub_en_premium.mp4',
    featured: true,
    orientation: 'horizontal',
  },
  {
    id: 'pitch-sala-situacional',
    src: './assets/videos/geopolem_pitch_video_sala_situacional.mp4',
    poster: './assets/videos/posters/geopolem_pitch_video_sala_situacional.jpg',
    title: 'Pitch · Sala situacional editorial',
    category: 'pitch',
    language: 'ES',
    subtitles: [],
    duration: '00:45',
    description: 'Pitch institucional en español: GEOPÓLEM como sala situacional editorial para lectores estratégicos.',
    strategic: 'Mensaje para aliados editoriales, inversores y partners institucionales.',
    source: 'geopolem_pitch_video_sala_situacional.mp4',
    featured: true,
    orientation: 'horizontal',
  },
  {
    id: 'pitch-english',
    src: './assets/videos/geopolem_pitch_video_english_subtitles.mp4',
    poster: './assets/videos/posters/geopolem_pitch_video_english_subtitles.jpg',
    title: 'Pitch · Editorial situation room (EN)',
    category: 'pitch',
    language: 'ES',
    subtitles: ['EN'],
    duration: '00:45',
    description: 'Versión con subtítulos en inglés del pitch institucional GEOPÓLEM, pensada para audiencias internacionales.',
    strategic: 'Apertura a alianzas con outlets y think tanks en mercados anglófonos.',
    source: 'geopolem_pitch_video_english_subtitles.mp4',
    featured: false,
    orientation: 'horizontal',
  },
  {
    id: 'reel-drones',
    src: './assets/videos/geopolem_reel_drones_en_subtitles.mp4',
    poster: './assets/videos/posters/geopolem_reel_drones_en_subtitles.jpg',
    title: 'Reel · Guerra de drones',
    category: 'drones',
    language: 'ES',
    subtitles: ['EN'],
    duration: '00:30',
    description: 'Reel vertical sobre la transformación del campo de batalla por los enjambres de drones FPV y la doctrina anti-drone.',
    strategic: 'Cambio doctrinal: la guerra híbrida ya no se mide solo en blindados, sino en operadores remotos y guerra electrónica.',
    source: 'geopolem_reel_drones_en_subtitles.mp4',
    featured: true,
    orientation: 'vertical',
  },
  {
    id: 'canal-estambul',
    src: './assets/videos/geopolem_canal_estambul_reel_es.mp4',
    poster: './assets/videos/posters/geopolem_canal_estambul_reel_es.jpg',
    title: 'Canal de Estambul · Geopolítica del Bósforo',
    category: 'chokepoints',
    language: 'ES',
    subtitles: [],
    duration: '00:40',
    description: 'Reel sobre el Canal de Estambul: ¿alternativa al Bósforo o palanca geopolítica para reescribir Montreux?',
    strategic: 'Si Turquía controla un canal paralelo, redefine el régimen de paso para la flota rusa del Mar Negro.',
    source: 'geopolem_canal_estambul_reel_es.mp4',
    featured: false,
    orientation: 'vertical',
  },
  {
    id: 'turquia-siguiente',
    src: './assets/videos/geopolem_turquia_siguiente_reel_es.mp4',
    poster: './assets/videos/posters/geopolem_turquia_siguiente_reel_es.jpg',
    title: 'Turquía, la siguiente potencia bisagra',
    category: 'doctrina',
    language: 'ES',
    subtitles: [],
    duration: '00:35',
    description: 'Reel editorial: por qué Turquía es el actor bisagra entre OTAN, BRICS+ y el corredor euroasiático.',
    strategic: 'Ankara como árbitro entre bloques: drones, gas, granos y rutas. Vigilar antes que reaccionar.',
    source: 'geopolem_turquia_siguiente_reel_es.mp4',
    featured: false,
    orientation: 'vertical',
  },
  {
    id: 'stablecoins',
    src: './assets/videos/geopolem_stablecoins_reel_geopolem.mp4',
    poster: './assets/videos/posters/geopolem_stablecoins_reel_geopolem.jpg',
    title: 'Stablecoins · Dolarización digital',
    category: 'finanzas',
    language: 'ES',
    subtitles: [],
    duration: '00:45',
    description: 'Reel sobre stablecoins, dolarización digital y la nueva arquitectura del eurodólar tokenizado.',
    strategic: 'El dólar se extiende vía stablecoins privadas; los Estados pierden monopolio monetario sin disparar un tiro.',
    source: 'geopolem_stablecoins_reel_geopolem.mp4',
    featured: false,
    orientation: 'vertical',
  },
  {
    id: 'water-crisis',
    src: './assets/videos/geopolem_water_crisis_reel_es.mp4',
    poster: './assets/videos/posters/geopolem_water_crisis_reel_es.jpg',
    title: 'Crisis global del agua',
    category: 'agua',
    language: 'ES',
    subtitles: [],
    duration: '00:50',
    description: 'Reel sobre la crisis hídrica global: acuíferos en colapso, presas geopolíticas y el agua como nuevo activo estratégico.',
    strategic: 'El agua es la próxima frontera de conflicto: del Nilo al Indo, del Tigris al Colorado.',
    source: 'geopolem_water_crisis_reel_es.mp4',
    featured: false,
    orientation: 'vertical',
  },
  {
    id: 'artico-osint',
    src: './assets/videos/geopolem_reel_artico_osint_es_sub_en_final.mp4',
    poster: './assets/videos/posters/geopolem_reel_artico_osint_es_sub_en_final.jpg',
    title: 'Ártico · OSINT del deshielo',
    category: 'artico',
    language: 'ES',
    subtitles: ['EN'],
    duration: '00:45',
    description: 'Análisis OSINT del Ártico: bases rusas, despliegues OTAN y el deshielo que abre la Ruta del Norte.',
    strategic: 'El Ártico deja de ser periferia y se convierte en teatro central de competencia entre EEUU, Rusia y China.',
    source: 'geopolem_reel_artico_osint_es_sub_en_final.mp4',
    featured: true,
    orientation: 'vertical',
  },
  {
    id: 'artico-rutas',
    src: './assets/videos/geopolem_reel_artico_guerra_rutas_es_sub_en.mp4',
    poster: './assets/videos/posters/geopolem_reel_artico_guerra_rutas_es_sub_en.jpg',
    title: 'Ártico · Guerra de rutas',
    category: 'artico',
    language: 'ES',
    subtitles: ['EN'],
    duration: '00:50',
    description: 'Reel sobre la pugna por las rutas marítimas árticas: NSR rusa, Northwest Passage y la Polar Silk Road china.',
    strategic: 'Quien controla la ruta polar acorta la geografía global y reescribe el coste de la energía y el comercio.',
    source: 'geopolem_reel_artico_guerra_rutas_es_sub_en.mp4',
    featured: false,
    orientation: 'vertical',
  },
  {
    id: 'hormuz-chokepoint',
    src: './assets/videos/geopolem_reel_hormuz_chokepoint_digital_es_sub_en.mp4',
    poster: './assets/videos/posters/geopolem_reel_hormuz_chokepoint_digital_es_sub_en.jpg',
    title: 'Hormuz · Chokepoint digital',
    category: 'chokepoints',
    language: 'ES',
    subtitles: ['EN'],
    duration: '01:10',
    description: 'Reel sobre el estrecho de Ormuz como chokepoint físico y digital: GPS spoofing, ciberataques y guerra cognitiva.',
    strategic: 'El estrangulamiento ya no es solo naval: cables, sensores y narrativas también pueden cortarse.',
    source: 'geopolem_reel_hormuz_chokepoint_digital_es_sub_en.mp4',
    featured: true,
    orientation: 'vertical',
  },
  {
    id: 'mundo-tripolar',
    src: './assets/videos/geopolem_reel_mundo_tripolar_es_sub_en.mp4',
    poster: './assets/videos/posters/geopolem_reel_mundo_tripolar_es_sub_en.jpg',
    title: 'Mundo tripolar',
    category: 'tripolar',
    language: 'ES',
    subtitles: ['EN'],
    duration: '00:55',
    description: 'Reel editorial: el fin del unipolarismo y la consolidación de un orden tripolar EEUU–China–coalición intermedia.',
    strategic: 'El sistema-mundo se está rearmando alrededor de tres polos. Pensar en bilateral es ya pensar en obsoleto.',
    source: 'geopolem_reel_mundo_tripolar_es_sub_en.mp4',
    featured: true,
    orientation: 'vertical',
  },
  {
    id: 'osint-venezuela',
    src: './assets/videos/geopolem_reel_osint_trump_venezuela_es_sub_en.mp4',
    poster: './assets/videos/posters/geopolem_reel_osint_trump_venezuela_es_sub_en.jpg',
    title: 'OSINT · Trump–Venezuela',
    category: 'osint',
    language: 'ES',
    subtitles: ['EN'],
    duration: '00:50',
    description: 'OSINT sobre la doctrina Trump 2.0 hacia Venezuela: presión naval en el Caribe, petróleo y migración.',
    strategic: 'Venezuela es laboratorio de la nueva política exterior estadounidense: coerción híbrida sin guerra abierta.',
    source: 'geopolem_reel_osint_trump_venezuela_es_sub_en.mp4',
    featured: false,
    orientation: 'vertical',
  },
  {
    id: 'mearsheimer-mathews',
    src: './assets/videos/geopolem_reel_mearsheimer_mathews_es_sub_en.mp4',
    poster: './assets/videos/posters/geopolem_reel_mearsheimer_mathews_es_sub_en.jpg',
    title: 'Mearsheimer vs Mathews',
    category: 'doctrina',
    language: 'ES',
    subtitles: ['EN'],
    duration: '01:00',
    description: 'Reel doctrinal: realismo ofensivo de Mearsheimer frente al institucionalismo de Mathews ante la crisis del orden liberal.',
    strategic: 'Marco mental para leer Ucrania, Taiwán y Oriente Medio sin caer en el reduccionismo ideológico.',
    source: 'geopolem_reel_mearsheimer_mathews_es_sub_en.mp4',
    featured: false,
    orientation: 'vertical',
  },
  {
    id: 'otan-retiro-eeuu',
    src: './assets/videos/geopolem_reel_osint_otan_retiro_eeuu_es_sub_en_final.mp4',
    poster: './assets/videos/posters/geopolem_reel_osint_otan_retiro_eeuu_es_sub_en_final.jpg',
    title: 'OSINT · OTAN sin EEUU',
    category: 'osint',
    language: 'ES',
    subtitles: ['EN'],
    duration: '01:00',
    description: 'OSINT sobre el escenario de retirada estadounidense de la OTAN: brechas de mando, paraguas nuclear y rearme europeo.',
    strategic: 'Si EEUU pivota a Indo-Pacífico, Europa hereda su propia defensa: ¿con qué doctrina y qué presupuesto?',
    source: 'geopolem_reel_osint_otan_retiro_eeuu_es_sub_en_final.mp4',
    featured: true,
    orientation: 'vertical',
  },
  {
    id: 'otan-retiro-30s',
    src: './assets/videos/geopolem_reel_osint_otan_retiro_eeuu_30s_es_sub_en.mp4',
    poster: './assets/videos/posters/geopolem_reel_osint_otan_retiro_eeuu_30s_es_sub_en.jpg',
    title: 'OSINT · OTAN sin EEUU · 30s',
    category: 'osint',
    language: 'ES',
    subtitles: ['EN'],
    duration: '00:30',
    description: 'Versión corta (30s) del briefing OSINT sobre la posible retirada estadounidense de la OTAN.',
    strategic: 'Formato corto para redes verticales: el mismo argumento, comprimido a alto impacto.',
    source: 'geopolem_reel_osint_otan_retiro_eeuu_30s_es_sub_en.mp4',
    featured: false,
    orientation: 'vertical',
  },
  {
    id: 'opep-fragmentacion',
    src: './assets/videos/geopolem_reel_opep_fragmentacion_es_sub_en.mp4',
    poster: './assets/videos/posters/geopolem_reel_opep_fragmentacion_es_sub_en.jpg',
    title: 'OPEP · Fragmentación energética',
    category: 'energia',
    language: 'ES',
    subtitles: ['EN'],
    duration: '00:45',
    description: 'Reel sobre la fragmentación interna de la OPEP+: tensiones Riad–Moscú, cuotas, dolarización y demanda china.',
    strategic: 'El cartel ya no fija precio; lo negocia en un tablero multipolar donde China e India son los nuevos árbitros.',
    source: 'geopolem_reel_opep_fragmentacion_es_sub_en.mp4',
    featured: false,
    orientation: 'vertical',
  },
];

export const VIDEO_TOTAL_COUNT = VIDEOS.length;
